export type SttEvaluationStatus = "tested" | "pending" | "blocked";

export interface SttEvaluationResult {
  modelId: string;
  label: string;
  status: SttEvaluationStatus;
  rank?: number;
  normalizedMatches?: number;
  exactMatches?: number;
  totalCases?: number;
  averageWer?: number;
  latencyP50Ms?: number;
  latencyP95Ms?: number;
  realTimeFactorP50?: number;
  strongestCategory?: string;
  weakestCategory?: string;
  notes?: string;
}

export const STT_EVALUATION_RUN = {
  generatedAt: "2026-06-07T05:27:46Z",
  suite: "Mini LibriSpeech real speech",
  corpus:
    "35 OpenSLR Mini LibriSpeech dev-clean-2 WAV clips with post-processing disabled",
  limitations:
    "Clean read-speech coverage only. It does not yet cover casual dictation, meeting-room audio, code dictation, accents, noise, or long-form chunking. Gemma 4 E2B Audio 4-bit (MLX) was added on 2026-06-07, and Higgs Audio v3 STT on 2026-06-16, via the app /v1/transcribe API rather than the offline harness (both are sidecar-backed live engines the harness rejects).",
  metricGuide: [
    "Rank: #1 is best for this suite.",
    "WER: lower is better.",
    "Match: higher is better.",
    "p50 latency: lower is faster.",
    "RTF: lower is faster; below 1.00 is faster than real time.",
  ],
  reportPath:
    "output/stt-realworld-model-eval-net-new-2026-06-07/2026-06-07T05-27-46/stt-realworld-net-new-summary.md",
};

export const STT_EVALUATION_RESULTS: SttEvaluationResult[] = [
  {
    modelId: "mlx-fireredasr2-aed",
    label: "FireRedASR2 AED (MLX)",
    status: "tested",
    rank: 1,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.029523809,
    latencyP50Ms: 242,
    latencyP95Ms: 311,
    realTimeFactorP50: 0.1001957,
    notes:
      "Best WER in this full app-available STT run; passed all 35 real-speech clips through the repaired MLX runtime.",
  },
  {
    modelId: "apple-speech-analyzer",
    label: "Apple Speech",
    status: "tested",
    rank: 2,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.032653064,
    latencyP50Ms: 68,
    latencyP95Ms: 76,
    realTimeFactorP50: 0.028691987,
    notes:
      "Best built-in system result with very low latency and no downloadable model footprint.",
  },
  {
    modelId: "mlx-parakeet-v3",
    label: "Parakeet V3 (MLX)",
    status: "tested",
    rank: 3,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.035238095,
    latencyP50Ms: 45,
    latencyP95Ms: 50,
    realTimeFactorP50: 0.018737271,
    notes:
      "Best speed/accuracy balance in the MLX group; top-tier WER with the lowest p50 latency among leading rows.",
  },
  {
    modelId: "moonshine-medium-streaming-en",
    label: "Moonshine V2 Medium",
    status: "tested",
    rank: 4,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.035238095,
    latencyP50Ms: 201,
    latencyP95Ms: 220,
    realTimeFactorP50: 0.082397,
    notes:
      "Best Moonshine result and tied Parakeet MLX on WER, but with higher latency.",
  },
  {
    modelId: "mlx-qwen3-asr",
    label: "Qwen3 ASR (MLX)",
    status: "tested",
    rank: 5,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.036666665,
    latencyP50Ms: 194,
    latencyP95Ms: 223,
    realTimeFactorP50: 0.08382353,
    notes: "Strong MLX ASR result with low latency for its accuracy tier.",
  },
  {
    modelId: "mlx-mega-asr",
    label: "Mega-ASR 8-bit (MLX)",
    status: "tested",
    rank: 7,
    normalizedMatches: 30,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.044,
    latencyP50Ms: 228,
    latencyP95Ms: 277,
    realTimeFactorP50: 0.1,
    notes:
      "Full 35-clip Mini LibriSpeech run completed on June 7, 2026 through the MLX audio regression sidecar after server dependency packaging repairs; strong WER with moderate latency.",
  },
  {
    modelId: "mlx-nemotron-asr-streaming-0.6b",
    label: "Nemotron 3.5 ASR Streaming 0.6B (MLX)",
    status: "tested",
    rank: 6,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.041,
    latencyP50Ms: 100,
    latencyP95Ms: 113,
    realTimeFactorP50: 0.04,
    notes:
      "Full 35-clip Mini LibriSpeech run completed on June 7, 2026 after the app-managed mlx-audio 0.4.4 runtime fix; fastest MLX ASR row in this tier.",
  },
  {
    modelId: "breeze-asr",
    label: "Breeze ASR",
    status: "tested",
    rank: 8,
    normalizedMatches: 30,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.045714285,
    latencyP50Ms: 718,
    latencyP95Ms: 759,
    realTimeFactorP50: 0.30119047,
    notes:
      "Strong accuracy, but slower than the top Parakeet, Apple, Qwen3, and Moonshine options.",
  },
  {
    modelId: "higgs-audio-v3-stt",
    label: "Higgs Audio v3 STT",
    status: "tested",
    rank: 9,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.046462585,
    latencyP50Ms: 1034,
    latencyP95Ms: 1102,
    realTimeFactorP50: 0.43730159,
    notes:
      "Measured via the app /v1/transcribe API on the same 35-clip Mini LibriSpeech suite, matching the Gemma methodology — Higgs is a sidecar-backed live engine the offline STT harness rejects. Strong clean-speech accuracy (29/35 normalized); the few misses are proper nouns and homophones (KALIKO→calico, course→chorus). At ~1 s/clip (RTF 0.44) it is far slower than the MLX and Parakeet leaders.",
  },
  {
    modelId: "mlx-qwen3-asr-0.6b",
    label: "Qwen3 ASR 0.6B (MLX)",
    status: "tested",
    rank: 10,
    normalizedMatches: 30,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.04952381,
    latencyP50Ms: 99,
    latencyP95Ms: 111,
    realTimeFactorP50: 0.042596348,
    notes:
      "Smaller Qwen3 ASR MLX checkpoint; lower latency than the 1.7B model with a modest WER tradeoff.",
  },
  {
    modelId: "parakeet-tdt-0.6b-v3",
    label: "Parakeet V3",
    status: "tested",
    rank: 11,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.052380953,
    latencyP50Ms: 87,
    latencyP95Ms: 92,
    realTimeFactorP50: 0.036472946,
    notes:
      "Best native Parakeet result and a strong low-latency non-MLX option.",
  },
  {
    modelId: "parakeet-tdt-0.6b-v2",
    label: "Parakeet V2",
    status: "tested",
    rank: 12,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.05268708,
    latencyP50Ms: 83,
    latencyP95Ms: 85,
    realTimeFactorP50: 0.034068137,
    notes:
      "Nearly identical to Parakeet V3 with slightly lower normalized matches.",
  },
  {
    modelId: "mlx-voxtral-mini-3b",
    label: "Voxtral Mini 3B (MLX)",
    status: "tested",
    rank: 13,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.059319727,
    latencyP50Ms: 1118,
    latencyP95Ms: 1183,
    realTimeFactorP50: 0.4681542,
    notes:
      "Passed after the Voxtral runtime EOS-token patch; accurate but much slower than Parakeet, Qwen3, and Apple Speech.",
  },
  {
    modelId: "mlx-whisper-large-v3-turbo",
    label: "Whisper Large V3 Turbo (MLX)",
    status: "tested",
    rank: 14,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.060748298,
    latencyP50Ms: 781,
    latencyP95Ms: 789,
    realTimeFactorP50: 0.3222904,
    notes:
      "Good MLX Whisper accuracy after snapshot metadata repair, but slower than the best local ASR choices here.",
  },
  {
    modelId: "moonshine-base",
    label: "Moonshine Base",
    status: "tested",
    rank: 15,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.060952384,
    latencyP50Ms: 55,
    latencyP95Ms: 72,
    realTimeFactorP50: 0.024344567,
    notes:
      "Very fast high-accuracy Moonshine result, behind only the top accuracy group.",
  },
  {
    modelId: "apple-speech-progressive",
    label: "Apple Speech (Progressive)",
    status: "tested",
    rank: 16,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.06173469,
    latencyP50Ms: 71,
    latencyP95Ms: 80,
    realTimeFactorP50: 0.030379746,
    notes:
      "Progressive Apple Speech coverage is usable, though weaker than offline Apple Speech on this suite.",
  },
  {
    modelId: "moonshine-small-streaming-en",
    label: "Moonshine V2 Small",
    status: "tested",
    rank: 17,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.062380955,
    latencyP50Ms: 120,
    latencyP95Ms: 133,
    realTimeFactorP50: 0.049345795,
    notes:
      "Good middle point between Moonshine Tiny speed and Moonshine Medium accuracy.",
  },
  {
    modelId: "mlx-voxtral-mini-4b-realtime",
    label: "Voxtral Mini 4B Realtime (MLX)",
    status: "tested",
    rank: 18,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07095238,
    latencyP50Ms: 1398,
    latencyP95Ms: 1503,
    realTimeFactorP50: 0.57420635,
    notes:
      "Realtime Voxtral MLX checkpoint is covered, but slower and less accurate than Voxtral Mini 3B here.",
  },
  {
    modelId: "sense-voice-int8",
    label: "SenseVoice",
    status: "tested",
    rank: 19,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07785714,
    latencyP50Ms: 208,
    latencyP95Ms: 226,
    realTimeFactorP50: 0.08553971,
    notes:
      "Broad multilingual engine; English clean-speech WER trails the top local choices on this corpus.",
  },
  {
    modelId: "moonshine-tiny-streaming-en",
    label: "Moonshine V2 Tiny",
    status: "tested",
    rank: 20,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07931972,
    latencyP50Ms: 43,
    latencyP95Ms: 52,
    realTimeFactorP50: 0.018574513,
    notes:
      "Fastest Moonshine streaming row, with a clear accuracy tradeoff versus Small and Medium.",
  },
  {
    modelId: "medium",
    label: "Whisper Medium",
    status: "tested",
    rank: 21,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07931972,
    latencyP50Ms: 340,
    latencyP95Ms: 358,
    realTimeFactorP50: 0.14404762,
    notes:
      "Standard Whisper Medium remains accurate, but trails the best modern local engines on both WER and latency.",
  },
  {
    modelId: "turbo",
    label: "Whisper Turbo",
    status: "tested",
    rank: 22,
    normalizedMatches: 26,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08217687,
    latencyP50Ms: 452,
    latencyP95Ms: 461,
    realTimeFactorP50: 0.18773006,
    notes:
      "Whisper Turbo is usable, but this run favors Breeze, MLX Whisper, and smaller streaming models.",
  },
  {
    modelId: "whisper-medium-q4_1",
    label: "Whisper Medium Q4",
    status: "tested",
    rank: 23,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08503401,
    latencyP50Ms: 337,
    latencyP95Ms: 357,
    realTimeFactorP50: 0.13924052,
    notes:
      "Quantized Whisper Medium keeps latency close to Medium but did not improve WER on this corpus.",
  },
  {
    modelId: "small.en",
    label: "Whisper Small English",
    status: "tested",
    rank: 24,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08646258,
    latencyP50Ms: 126,
    latencyP95Ms: 142,
    realTimeFactorP50: 0.053955376,
    notes:
      "English-only Whisper Small is compact and fast, but lower ranked on clean real speech here.",
  },
  {
    modelId: "medium.en",
    label: "Whisper Medium English",
    status: "tested",
    rank: 25,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08646258,
    latencyP50Ms: 336,
    latencyP95Ms: 356,
    realTimeFactorP50: 0.14092827,
    notes:
      "English-only Whisper Medium did not beat multilingual Medium on this corpus.",
  },
  {
    modelId: "mlx-distil-whisper-large-v3",
    label: "Distil-Whisper Large V3 (MLX)",
    status: "tested",
    rank: 26,
    normalizedMatches: 26,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.099319726,
    latencyP50Ms: 768,
    latencyP95Ms: 772,
    realTimeFactorP50: 0.31533745,
    notes:
      "MLX Distil-Whisper runs after snapshot repair, but trailed full MLX Whisper Turbo on this suite.",
  },
  {
    modelId: "small",
    label: "Whisper Small",
    status: "tested",
    rank: 27,
    normalizedMatches: 24,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.10340136,
    latencyP50Ms: 127,
    latencyP95Ms: 140,
    realTimeFactorP50: 0.0535865,
    notes:
      "Whisper Small is a reliable compact baseline, with a clear WER gap from the top rows.",
  },
  {
    modelId: "base",
    label: "Whisper Base",
    status: "tested",
    rank: 28,
    normalizedMatches: 23,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.11241496,
    latencyP50Ms: 52,
    latencyP95Ms: 59,
    realTimeFactorP50: 0.022462202,
    notes:
      "Whisper Base is very fast, but accuracy is materially lower than Small and newer engines.",
  },
  {
    modelId: "tiny.en",
    label: "Whisper Tiny English",
    status: "tested",
    rank: 29,
    normalizedMatches: 22,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.118367344,
    latencyP50Ms: 34,
    latencyP95Ms: 39,
    realTimeFactorP50: 0.014883721,
    notes:
      "Tiny English is very fast and suitable only where accuracy tradeoffs are acceptable.",
  },
  {
    modelId: "base.en",
    label: "Whisper Base English",
    status: "tested",
    rank: 30,
    normalizedMatches: 23,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.12273242,
    latencyP50Ms: 53,
    latencyP95Ms: 58,
    realTimeFactorP50: 0.022325581,
    notes:
      "Base English did not improve over multilingual Base in this app-available run.",
  },
  {
    modelId: "tiny",
    label: "Whisper Tiny",
    status: "tested",
    rank: 31,
    normalizedMatches: 22,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.1314626,
    latencyP50Ms: 35,
    latencyP95Ms: 44,
    realTimeFactorP50: 0.014606741,
    notes: "Fastest Whisper.cpp row, but ranked near the bottom on WER.",
  },
  {
    modelId: "large",
    label: "Whisper Large",
    status: "tested",
    rank: 32,
    normalizedMatches: 20,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.13526078,
    latencyP50Ms: 658,
    latencyP95Ms: 687,
    realTimeFactorP50: 0.27651823,
    notes:
      "Whisper Large underperformed the Turbo and Medium variants on this short clean-speech corpus.",
  },
  {
    modelId: "gemma4-e2b-audio-mlx",
    label: "Gemma 4 E2B Audio 4-bit (MLX)",
    status: "tested",
    rank: 33,
    normalizedMatches: 9,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.367,
    latencyP50Ms: 283,
    notes:
      "Measured via the app /v1/transcribe API (this live Gemma engine is not in the offline STT harness, which lacks mlx_vlm) on the same 35-clip Mini LibriSpeech suite. Output is inconsistent: some clips transcribe cleanly, others truncate or hallucinate.",
  },
  {
    modelId: "gigaam-v3-e2e-ctc",
    label: "GigaAM v3",
    status: "tested",
    rank: 34,
    normalizedMatches: 0,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.7282653,
    latencyP50Ms: 75,
    latencyP95Ms: 81,
    realTimeFactorP50: 0.03080169,
    strongestCategory: "Russian ASR use cases",
    weakestCategory: "English LibriSpeech clean speech",
    notes:
      "Russian-specialized model. It now runs with the repaired vocab file, but this English LibriSpeech suite is outside its target language.",
  },
];

export function getSttEvaluationResult(
  modelId: string,
): SttEvaluationResult | undefined {
  return STT_EVALUATION_RESULTS.find((result) => result.modelId === modelId);
}
