export type SttEvaluationStatus = "tested" | "pending" | "blocked";

export interface SttEvaluationResult {
  modelId: string;
  label: string;
  status: SttEvaluationStatus;
  rank?: number;
  normalizedMatches?: number;
  exactMatches?: number;
  totalCases?: number;
  averageWer?: number;
  latencyP50Ms?: number;
  latencyP95Ms?: number;
  realTimeFactorP50?: number;
  strongestCategory?: string;
  weakestCategory?: string;
  notes?: string;
}

export const STT_EVALUATION_RUN = {
  generatedAt: "2026-05-12T03:38:57.364Z",
  suite: "Mini LibriSpeech real speech",
  corpus:
    "35 OpenSLR Mini LibriSpeech dev-clean-2 WAV clips with post-processing disabled",
  limitations:
    "Clean read-speech coverage only. It does not yet cover casual dictation, meeting-room audio, code dictation, accents, noise, or long-form chunking.",
  metricGuide: [
    "Rank: #1 is best for this suite.",
    "WER: lower is better.",
    "Match: higher is better.",
    "p50 latency: lower is faster.",
    "RTF: lower is faster; below 1.00 is faster than real time.",
  ],
  reportPath:
    "output/stt-realworld-model-eval/2026-05-12T03-38-25/stt-realworld-new-mlx-summary.md",
};

export const STT_EVALUATION_RESULTS: SttEvaluationResult[] = [
  {
    modelId: "mlx-fireredasr2-aed",
    label: "FireRedASR2 AED (MLX)",
    status: "tested",
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.029523809,
    latencyP50Ms: 235,
    latencyP95Ms: 303,
    realTimeFactorP50: 0.09790576,
    notes:
      "Best full-suite WER among the tested MLX-Audio additions; passed all 35 real-speech clips.",
    rank: 1,
  },
  {
    modelId: "apple-speech-analyzer",
    label: "Apple Speech",
    status: "tested",
    rank: 2,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.032653064,
    latencyP50Ms: 88,
    latencyP95Ms: 99,
    realTimeFactorP50: 0.0372807,
    notes:
      "Best WER in the fresh real-speech run with fast app-runtime Apple SpeechAnalyzer coverage.",
  },
  {
    modelId: "mlx-parakeet-v3",
    label: "Parakeet V3 (MLX)",
    status: "tested",
    rank: 3,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.035238095,
    latencyP50Ms: 55,
    latencyP95Ms: 60,
    realTimeFactorP50: 0.022807019,
    notes:
      "Best speed/accuracy balance in the fresh run: top-tier WER with the lowest p50 latency among leading models.",
  },
  {
    modelId: "moonshine-medium-streaming-en",
    label: "Moonshine V2 Medium",
    status: "tested",
    rank: 4,
    normalizedMatches: 32,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.035238095,
    latencyP50Ms: 229,
    latencyP95Ms: 256,
    realTimeFactorP50: 0.094523326,
    notes: "Tied Parakeet V3 MLX on WER, but with higher latency.",
  },
  {
    modelId: "mlx-qwen3-asr",
    label: "Qwen3 ASR (MLX)",
    status: "tested",
    rank: 5,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.036666665,
    latencyP50Ms: 234,
    latencyP95Ms: 269,
    realTimeFactorP50: 0.10147059,
    notes:
      "Strong MLX ASR result, just behind Apple Speech, Parakeet MLX, and Moonshine Medium on WER.",
  },
  {
    modelId: "breeze-asr",
    label: "Breeze ASR",
    status: "tested",
    rank: 6,
    normalizedMatches: 30,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.045714285,
    latencyP50Ms: 826,
    latencyP95Ms: 875,
    realTimeFactorP50: 0.346856,
    notes:
      "Strong accuracy, but much slower than the top Parakeet and Moonshine options.",
  },
  {
    modelId: "mlx-qwen3-asr-0.6b",
    label: "Qwen3 ASR 0.6B (MLX)",
    status: "tested",
    normalizedMatches: 30,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.04952381,
    latencyP50Ms: 103,
    latencyP95Ms: 122,
    realTimeFactorP50: 0.044607844,
    notes:
      "Full 35-clip Mini LibriSpeech suite passed with the fastest p50 latency among the new MLX-Audio ASR additions.",
    rank: 7,
  },
  {
    modelId: "parakeet-tdt-0.6b-v3",
    label: "Parakeet V3",
    status: "tested",
    rank: 8,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.052380953,
    latencyP50Ms: 89,
    latencyP95Ms: 104,
    realTimeFactorP50: 0.03801296,
    notes: "Best native Parakeet result and a strong low-latency option.",
  },
  {
    modelId: "parakeet-tdt-0.6b-v2",
    label: "Parakeet V2",
    status: "tested",
    rank: 9,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.05268708,
    latencyP50Ms: 84,
    latencyP95Ms: 89,
    realTimeFactorP50: 0.034439832,
    notes:
      "Nearly identical to Parakeet V3 with slightly lower normalized matches.",
  },
  {
    modelId: "mlx-voxtral-mini-3b",
    label: "Voxtral Mini 3B (MLX)",
    status: "tested",
    rank: 10,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.059319727,
    latencyP50Ms: 1456,
    latencyP95Ms: 1552,
    realTimeFactorP50: 0.61257607,
    notes:
      "Accurate Voxtral MLX run, but much slower than Parakeet, Qwen3, and Apple Speech.",
  },
  {
    modelId: "mlx-whisper-large-v3-turbo",
    label: "Whisper Large V3 Turbo (MLX)",
    status: "tested",
    rank: 11,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.060748298,
    latencyP50Ms: 908,
    latencyP95Ms: 921,
    realTimeFactorP50: 0.3726141,
    notes:
      "Good MLX Whisper accuracy, but slower than the best local ASR choices here.",
  },
  {
    modelId: "moonshine-base",
    label: "Moonshine Base",
    status: "tested",
    rank: 12,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.060952384,
    latencyP50Ms: 65,
    latencyP95Ms: 85,
    realTimeFactorP50: 0.028464418,
    notes:
      "Very fast high-accuracy Moonshine result, behind only the top accuracy group.",
  },
  {
    modelId: "apple-speech-progressive",
    label: "Apple Speech (Progressive)",
    status: "tested",
    rank: 13,
    normalizedMatches: 31,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.06173469,
    latencyP50Ms: 84,
    latencyP95Ms: 104,
    realTimeFactorP50: 0.036764707,
    notes:
      "Progressive partial aggregation is fixed; WER is now normal and usable, though weaker than offline Apple Speech.",
  },
  {
    modelId: "moonshine-small-streaming-en",
    label: "Moonshine V2 Small",
    status: "tested",
    rank: 14,
    normalizedMatches: 29,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.062380955,
    latencyP50Ms: 143,
    latencyP95Ms: 161,
    realTimeFactorP50: 0.05869159,
    notes:
      "Good middle point between Moonshine Tiny speed and Moonshine Medium accuracy.",
  },
  {
    modelId: "mlx-voxtral-mini-4b-realtime",
    label: "Voxtral Mini 4B Realtime (MLX)",
    status: "tested",
    rank: 15,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07095238,
    latencyP50Ms: 2009,
    latencyP95Ms: 2086,
    realTimeFactorP50: 0.8114754,
    notes:
      "Realtime Voxtral MLX checkpoint is covered, but slower and less accurate than Voxtral Mini 3B here.",
  },
  {
    modelId: "sense-voice-int8",
    label: "SenseVoice",
    status: "tested",
    rank: 16,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07785714,
    latencyP50Ms: 217,
    latencyP95Ms: 235,
    realTimeFactorP50: 0.08880157,
    notes: "Good multilingual fallback with competitive real-speech WER.",
  },
  {
    modelId: "medium",
    label: "Whisper Medium",
    status: "tested",
    rank: 17,
    normalizedMatches: 28,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.07931972,
    latencyP50Ms: 404,
    latencyP95Ms: 433,
    realTimeFactorP50: 0.17044534,
    notes: "Best standard full-precision Whisper.cpp result in this run.",
  },
  {
    modelId: "turbo",
    label: "Whisper Turbo",
    status: "tested",
    rank: 18,
    normalizedMatches: 26,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08217687,
    latencyP50Ms: 534,
    latencyP95Ms: 545,
    realTimeFactorP50: 0.22090162,
    notes:
      "Large-v3 family model, but weaker here than Medium and the top non-Whisper models.",
  },
  {
    modelId: "whisper-medium-q4_1",
    label: "Whisper Medium Q4",
    status: "tested",
    rank: 19,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08503401,
    latencyP50Ms: 397,
    latencyP95Ms: 421,
    realTimeFactorP50: 0.16329114,
    notes:
      "Quantized Medium is close to full Medium with slightly better latency.",
  },
  {
    modelId: "small.en",
    label: "Whisper Small English",
    status: "tested",
    rank: 20,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08646258,
    latencyP50Ms: 152,
    latencyP95Ms: 168,
    realTimeFactorP50: 0.065314405,
    notes: "Best small Whisper variant in this run.",
  },
  {
    modelId: "medium.en",
    label: "Whisper Medium English",
    status: "tested",
    rank: 21,
    normalizedMatches: 27,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.08646258,
    latencyP50Ms: 395,
    latencyP95Ms: 420,
    realTimeFactorP50: 0.16632861,
    notes: "English-only Medium did not beat the multilingual Medium here.",
  },
  {
    modelId: "mlx-distil-whisper-large-v3",
    label: "Distil-Whisper Large V3 (MLX)",
    status: "tested",
    rank: 22,
    normalizedMatches: 26,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.099319726,
    latencyP50Ms: 886,
    latencyP95Ms: 896,
    realTimeFactorP50: 0.36434424,
    notes:
      "MLX Distil-Whisper coverage is active, but it trailed the full MLX Whisper Turbo checkpoint on this run.",
  },
  {
    modelId: "small",
    label: "Whisper Small",
    status: "tested",
    rank: 23,
    normalizedMatches: 24,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.10340136,
    latencyP50Ms: 154,
    latencyP95Ms: 170,
    realTimeFactorP50: 0.06540085,
    notes: "Lower accuracy than Small English with nearly identical latency.",
  },
  {
    modelId: "base",
    label: "Whisper Base",
    status: "tested",
    rank: 24,
    normalizedMatches: 23,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.11241496,
    latencyP50Ms: 62,
    latencyP95Ms: 71,
    realTimeFactorP50: 0.026774848,
    notes: "Fast baseline with expected accuracy tradeoffs.",
  },
  {
    modelId: "tiny.en",
    label: "Whisper Tiny English",
    status: "tested",
    rank: 25,
    normalizedMatches: 22,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.118367344,
    latencyP50Ms: 40,
    latencyP95Ms: 46,
    realTimeFactorP50: 0.017391304,
    notes: "Fastest Whisper variant with better WER than multilingual Tiny.",
  },
  {
    modelId: "base.en",
    label: "Whisper Base English",
    status: "tested",
    rank: 27,
    normalizedMatches: 23,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.12273242,
    latencyP50Ms: 62,
    latencyP95Ms: 69,
    realTimeFactorP50: 0.026511626,
    notes: "Similar speed to Whisper Base with worse WER here.",
  },
  {
    modelId: "tiny",
    label: "Whisper Tiny",
    status: "tested",
    rank: 28,
    normalizedMatches: 22,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.1314626,
    latencyP50Ms: 41,
    latencyP95Ms: 51,
    realTimeFactorP50: 0.017209303,
    notes: "Very fast, but lower accuracy than Tiny English.",
  },
  {
    modelId: "large",
    label: "Whisper Large",
    status: "tested",
    rank: 29,
    normalizedMatches: 20,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.13526078,
    latencyP50Ms: 756,
    latencyP95Ms: 795,
    realTimeFactorP50: 0.3192623,
    notes:
      "The quantized large-v3-q5 file underperformed Whisper Medium on this corpus.",
  },
  {
    modelId: "moonshine-tiny-streaming-en",
    label: "Moonshine V2 Tiny",
    status: "tested",
    rank: 30,
    normalizedMatches: 23,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.17234693,
    latencyP50Ms: 74,
    latencyP95Ms: 91,
    realTimeFactorP50: 0.03159923,
    notes:
      "Very fast and stable, but much weaker than larger Moonshine models.",
  },
  {
    modelId: "gigaam-v3-e2e-ctc",
    label: "GigaAM v3",
    status: "tested",
    rank: 26,
    normalizedMatches: 15,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 0.12202948,
    latencyP50Ms: 97,
    latencyP95Ms: 115,
    realTimeFactorP50: 0.03066113,
    strongestCategory: "Russian daily dictation",
    weakestCategory: "Russian numbers and dates",
    notes:
      "Rerun on the full 35-case Russian suite with macOS Milena audio; ranked with a language-specific corpus caveat.",
  },
  {
    modelId: "mlx-vibevoice-asr-bf16",
    label: "VibeVoice ASR 9B (MLX)",
    status: "tested",
    rank: 31,
    normalizedMatches: 0,
    exactMatches: 0,
    totalCases: 35,
    averageWer: 1.871,
    latencyP50Ms: 11005,
    latencyP95Ms: 12331,
    realTimeFactorP50: 4.74,
    notes:
      "Full 35-clip Mini LibriSpeech suite completed with no runner failures, but accuracy and latency are unsuitable for live dictation. Keep positioned for file transcription experiments, not low-latency dictation.",
  },
];

export function getSttEvaluationResult(
  modelId: string,
): SttEvaluationResult | undefined {
  return STT_EVALUATION_RESULTS.find((result) => result.modelId === modelId);
}
