export type TtsEvaluationStatus = "tested" | "failed" | "blocked";

export interface TtsEvaluationResult {
  modelId: string;
  label: string;
  status: TtsEvaluationStatus;
  rank?: number;
  sampleCount?: number;
  passedCases?: number;
  score?: number;
  asrAverageWer?: number;
  asrMedianWer?: number;
  latencyP50Ms?: number;
  realTimeFactorP50?: number;
  notes: string;
}

export const TTS_EVALUATION_RUN = {
  generatedAt: "2026-05-07T23:10:14Z",
  suite: "TTS real-world hard benchmark",
  corpus:
    "Five hard readback prompts covering casual text, long meeting summary, code and symbols, numbers/dates, and multilingual Spanish text.",
  limitations:
    "Scores are deterministic synthesis-health and latency proxies from generated WAVs. They do not yet include MOS listener ratings, ASR round-trip WER, emotion/style preference testing, or far-field playback capture.",
  reportPath: "output/tts-model-eval/tts-eval-summary.json",
};

export const TTS_EVALUATION_RESULTS: TtsEvaluationResult[] = [
  {
    modelId: "tts-sherpa-en-us-lessac-medium",
    label: "Sherpa Lessac Medium",
    status: "tested",
    rank: 1,
    sampleCount: 5,
    passedCases: 5,
    score: 99.5,
    latencyP50Ms: 736,
    realTimeFactorP50: 0.08,
    notes: "Fastest full-pass TTS model; passed all five real-world prompts.",
  },
  {
    modelId: "tts-sherpa-zh-cn-melo",
    label: "Sherpa Melo Chinese/English",
    status: "tested",
    rank: 2,
    sampleCount: 5,
    passedCases: 5,
    score: 97.7,
    latencyP50Ms: 4596,
    realTimeFactorP50: 0.47,
    notes:
      "Downloaded and fixed pack handling; the runner no longer passes a missing espeak data dir.",
  },
  {
    modelId: "kokoro-82m",
    label: "MLX Kokoro 82M",
    status: "tested",
    rank: 3,
    sampleCount: 5,
    passedCases: 5,
    score: 97.7,
    latencyP50Ms: 3256,
    realTimeFactorP50: 0.46,
    notes: "Best MLX Audio result in the five-case pass.",
  },
  {
    modelId: "ming-omni-0.5b",
    label: "MLX Ming-omni TTS 0.5B",
    status: "tested",
    rank: 4,
    sampleCount: 5,
    passedCases: 5,
    score: 97.1,
    latencyP50Ms: 5043,
    realTimeFactorP50: 0.75,
    notes: "Strong audio-health score with moderate median latency.",
  },
  {
    modelId: "qwen3-tts-0.6b-4bit",
    label: "MLX Qwen3 TTS 0.6B 4-bit",
    status: "tested",
    rank: 5,
    sampleCount: 5,
    passedCases: 5,
    score: 96.8,
    latencyP50Ms: 5084,
    realTimeFactorP50: 0.53,
    notes: "Fastest tested Qwen3 MLX variant in the full pass.",
  },
  {
    modelId: "kokoro-82m-v1.0",
    label: "Kokoro 82M",
    status: "tested",
    rank: 6,
    sampleCount: 5,
    passedCases: 5,
    score: 96.7,
    latencyP50Ms: 4994,
    realTimeFactorP50: 0.48,
    notes:
      "Managed runtime Kokoro passed all cases after stdout parsing was hardened.",
  },
  {
    modelId: "qwen3-tts-0.6b",
    label: "MLX Qwen3 TTS 0.6B",
    status: "tested",
    rank: 7,
    sampleCount: 5,
    passedCases: 5,
    score: 96.1,
    latencyP50Ms: 6548,
    realTimeFactorP50: 0.67,
    notes: "Reliable all-case Qwen3 MLX baseline.",
  },
  {
    modelId: "spark-tts-0.5b",
    label: "MLX Spark TTS 0.5B",
    status: "tested",
    rank: 8,
    sampleCount: 5,
    passedCases: 5,
    score: 95.9,
    latencyP50Ms: 7039,
    realTimeFactorP50: 0.78,
    notes: "Passed with the MLX bridge conditioning fallback.",
  },
  {
    modelId: "qwen3-tts-1.7b",
    label: "MLX Qwen3 TTS 1.7B VoiceDesign",
    status: "tested",
    rank: 9,
    sampleCount: 5,
    passedCases: 5,
    score: 95.5,
    latencyP50Ms: 7310,
    realTimeFactorP50: 0.84,
    notes: "VoiceDesign model used the bridge's default instruction prompt.",
  },
  {
    modelId: "qwen3-tts-1.7b-base",
    label: "MLX Qwen3 TTS 1.7B Base",
    status: "tested",
    rank: 10,
    sampleCount: 5,
    passedCases: 5,
    score: 95.4,
    latencyP50Ms: 7354,
    realTimeFactorP50: 0.84,
    notes: "Close to the VoiceDesign score without instruction prompting.",
  },
  {
    modelId: "qwen3-0.6b-base",
    label: "Qwen3 Native 0.6B Base",
    status: "tested",
    rank: 11,
    sampleCount: 5,
    passedCases: 5,
    score: 95.2,
    latencyP50Ms: 10061,
    realTimeFactorP50: 1.11,
    notes: "Native runtime installed into the current app runtime directory.",
  },
  {
    modelId: "qwen3-0.6b-customvoice",
    label: "Qwen3 Native 0.6B CustomVoice",
    status: "tested",
    rank: 12,
    sampleCount: 5,
    passedCases: 5,
    score: 94.5,
    latencyP50Ms: 18683,
    realTimeFactorP50: 1.26,
    notes:
      "Partial local install was repaired by downloading the missing Qwen tokenizer files.",
  },
  {
    modelId: "voxtral-tts-4b",
    label: "MLX Voxtral TTS 4B",
    status: "tested",
    rank: 13,
    sampleCount: 5,
    passedCases: 5,
    score: 94.3,
    latencyP50Ms: 8710,
    realTimeFactorP50: 1.15,
    notes: "Large MLX model passed all prompts with moderate median latency.",
  },
  {
    modelId: "pocket-tts-8bit",
    label: "MLX Pocket TTS 8-bit",
    status: "tested",
    rank: 14,
    sampleCount: 5,
    passedCases: 5,
    score: 93,
    latencyP50Ms: 10311,
    realTimeFactorP50: 1.04,
    notes: "Best Pocket TTS quantization in this run.",
  },
  {
    modelId: "openvoice",
    label: "OpenVoice",
    status: "tested",
    rank: 15,
    sampleCount: 5,
    passedCases: 5,
    score: 92.7,
    latencyP50Ms: 8708,
    realTimeFactorP50: 1.12,
    notes: "Passed using the current repo managed-runtime worker layout.",
  },
  {
    modelId: "chatterbox-mlx",
    label: "MLX Chatterbox",
    status: "tested",
    rank: 16,
    sampleCount: 5,
    passedCases: 5,
    score: 91.5,
    latencyP50Ms: 9551,
    realTimeFactorP50: 1.45,
    notes: "MLX Chatterbox was faster than the managed Chatterbox variants.",
  },
  {
    modelId: "pocket-tts",
    label: "MLX Pocket TTS",
    status: "tested",
    rank: 17,
    sampleCount: 5,
    passedCases: 5,
    score: 91.3,
    latencyP50Ms: 13627,
    realTimeFactorP50: 1.56,
    notes: "Full precision Pocket TTS passed all prompts.",
  },
  {
    modelId: "vibevoice-realtime-0-5b",
    label: "VibeVoice Realtime 0.5B",
    status: "tested",
    rank: 18,
    sampleCount: 5,
    passedCases: 5,
    score: 90.8,
    latencyP50Ms: 12929,
    realTimeFactorP50: 1.41,
    notes: "Runner now uses the speech-runtime venv expected by the app.",
  },
  {
    modelId: "csm-1b",
    label: "MLX CSM 1B",
    status: "tested",
    rank: 19,
    sampleCount: 5,
    passedCases: 5,
    score: 90.6,
    latencyP50Ms: 17765,
    realTimeFactorP50: 2.15,
    notes:
      "Passed the full rerun after a transient MLX name-resolution error in an earlier pass.",
  },
  {
    modelId: "qwen3-1.7b-customvoice",
    label: "Qwen3 Native 1.7B CustomVoice",
    status: "tested",
    rank: 20,
    sampleCount: 5,
    passedCases: 5,
    score: 89.9,
    latencyP50Ms: 35019,
    realTimeFactorP50: 2.41,
    notes: "Accurate but much slower than native Qwen3 0.6B.",
  },
  {
    modelId: "xtts-v2",
    label: "XTTS v2",
    status: "tested",
    rank: 21,
    sampleCount: 5,
    passedCases: 5,
    score: 87.1,
    latencyP50Ms: 23415,
    realTimeFactorP50: 2.59,
    notes:
      "Passed after testing against the repo runtime worker rather than the older installed worker.",
  },
  {
    modelId: "chatterbox-turbo",
    label: "Chatterbox Turbo",
    status: "tested",
    rank: 22,
    sampleCount: 5,
    passedCases: 5,
    score: 86.9,
    latencyP50Ms: 20832,
    realTimeFactorP50: 2.4,
    notes: "Turbo checkpoint layout is now handled by the repo runtime worker.",
  },
  {
    modelId: "pocket-tts-4bit",
    label: "MLX Pocket TTS 4-bit",
    status: "tested",
    rank: 23,
    sampleCount: 5,
    passedCases: 5,
    score: 86.3,
    latencyP50Ms: 13372,
    realTimeFactorP50: 1.5,
    notes: "Passed all prompts, behind the 8-bit Pocket TTS variant.",
  },
  {
    modelId: "lfm2-5-audio-1-5b-q4-0",
    label: "LFM2.5 Audio 1.5B GGUF Q4_0",
    status: "tested",
    rank: 24,
    sampleCount: 5,
    passedCases: 4,
    score: 85.8,
    latencyP50Ms: 2132,
    realTimeFactorP50: 0.24,
    notes:
      "Fast when it succeeds, but one case exited inside the native Liquid Audio runtime.",
  },
  {
    modelId: "dia-1.6b",
    label: "MLX Dia 1.6B",
    status: "tested",
    rank: 26,
    sampleCount: 5,
    passedCases: 5,
    score: 85.1,
    latencyP50Ms: 20995,
    realTimeFactorP50: 3.29,
    notes: "Reliable but slower than the leading MLX options.",
  },
  {
    modelId: "lfm2-5-audio-1-5b",
    label: "MLX LFM2.5 Audio 1.5B",
    status: "tested",
    rank: 27,
    sampleCount: 5,
    passedCases: 5,
    score: 81.3,
    latencyP50Ms: 33289,
    realTimeFactorP50: 3.78,
    notes:
      "Passed all cases, but the MLX path is much slower than the GGUF runner.",
  },
  {
    modelId: "chatterbox",
    label: "Chatterbox",
    status: "tested",
    rank: 28,
    sampleCount: 5,
    passedCases: 5,
    score: 80,
    latencyP50Ms: 29970,
    realTimeFactorP50: 3.46,
    notes:
      "Now uses a bundled fallback voice prompt when no clone profile is selected.",
  },
  {
    modelId: "chatterbox-multilingual",
    label: "Chatterbox Multilingual",
    status: "tested",
    rank: 29,
    sampleCount: 5,
    passedCases: 5,
    score: 79.3,
    latencyP50Ms: 26502,
    realTimeFactorP50: 3.99,
    notes: "Now uses the same bundled fallback prompt path as base Chatterbox.",
  },
  {
    modelId: "voxcpm2-4bit",
    label: "MLX VoxCPM2 4-bit",
    status: "tested",
    rank: 30,
    sampleCount: 5,
    passedCases: 5,
    score: 67.5,
    latencyP50Ms: 45450,
    realTimeFactorP50: 5.74,
    notes: "Passed all prompts, but latency is high.",
  },
  {
    modelId: "fish-audio-s2-pro",
    label: "MLX Fish Audio S2 Pro",
    status: "tested",
    rank: 31,
    sampleCount: 5,
    passedCases: 5,
    score: 65,
    latencyP50Ms: 160734,
    realTimeFactorP50: 18.23,
    notes: "Passed all prompts but was one of the slowest models in the suite.",
  },
  {
    modelId: "kugel-audio-7b",
    label: "MLX KugelAudio 7B",
    status: "tested",
    rank: 32,
    sampleCount: 5,
    passedCases: 1,
    score: 13,
    latencyP50Ms: 34103,
    realTimeFactorP50: 17.05,
    notes: "Only one case passed; four cases hit the 300 second timeout.",
  },
  {
    modelId: "bark-small",
    label: "MLX Bark Small",
    status: "tested",
    rank: 25,
    sampleCount: 5,
    passedCases: 5,
    score: 85.2,
    latencyP50Ms: 38393,
    realTimeFactorP50: 3.22,
    notes:
      "Passed all five cases on isolated rerun after a transient MLX name-resolution failure in the first full pass.",
  },
];

export function getTtsEvaluationResult(
  modelId: string,
): TtsEvaluationResult | undefined {
  return TTS_EVALUATION_RESULTS.find((result) => result.modelId === modelId);
}
