export type TtsEvaluationStatus = "tested" | "failed" | "blocked";

export interface TtsEvaluationResult {
  modelId: string;
  label: string;
  status: TtsEvaluationStatus;
  rank?: number;
  sampleCount?: number;
  passedCases?: number;
  score?: number;
  asrAverageWer?: number;
  asrMedianWer?: number;
  latencyP50Ms?: number;
  realTimeFactorP50?: number;
  notes: string;
}

export const TTS_EVALUATION_RUN = {
  generatedAt: "2026-05-12T03:19:44Z",
  suite: "TTS real-world hard benchmark",
  corpus:
    "Five hard readback prompts covering casual text, long meeting summary, code and symbols, numbers/dates, and multilingual Spanish text. Scores include local ASR round-trip WER.",
  limitations:
    "Scores combine synthesis success, ASR round-trip WER from the local faster-whisper judge, real-time factor, and generated-WAV health checks. They still do not include MOS listener ratings, emotion/style preference testing, or far-field playback capture; ASR judge errors can affect WER, especially code/symbol text.",
  metricGuide: [
    "Rank: #1 is best for this suite.",
    "Score and pass: higher is better.",
    "ASR WER: lower is better.",
    "p50 latency: lower is faster.",
    "RTF: lower is faster; below 1.00 is faster than real time.",
  ],
  reportPath:
    "output/tts-model-eval/full-new-mlx-2026-05-11/tts-eval-summary.json",
};

export const TTS_EVALUATION_RESULTS: TtsEvaluationResult[] = [
  {
    modelId: "tts-sherpa-en-us-lessac-medium",
    label: "Sherpa Lessac Medium",
    status: "tested",
    rank: 1,
    sampleCount: 5,
    passedCases: 5,
    score: 98.2,
    asrAverageWer: 0.0508,
    asrMedianWer: 0.0345,
    latencyP50Ms: 736,
    realTimeFactorP50: 0.08,
    notes: "Fastest full-pass TTS model; passed all five real-world prompts.",
  },
  {
    modelId: "kokoro-82m",
    label: "MLX Kokoro 82M",
    status: "tested",
    rank: 2,
    sampleCount: 5,
    passedCases: 5,
    score: 98.2,
    asrAverageWer: 0.016,
    asrMedianWer: 0,
    latencyP50Ms: 3256,
    realTimeFactorP50: 0.46,
    notes: "Best MLX Audio result in the five-case pass.",
  },
  {
    modelId: "kokoro-82m-v1.0",
    label: "Kokoro 82M",
    status: "tested",
    rank: 3,
    sampleCount: 5,
    passedCases: 5,
    score: 97.6,
    asrAverageWer: 0.016,
    asrMedianWer: 0,
    latencyP50Ms: 4994,
    realTimeFactorP50: 0.48,
    notes:
      "Managed runtime Kokoro passed all cases after stdout parsing was hardened.",
  },
  {
    modelId: "qwen3-tts-1.7b",
    label: "MLX Qwen3 TTS 1.7B VoiceDesign",
    status: "tested",
    rank: 4,
    sampleCount: 5,
    passedCases: 5,
    score: 96.8,
    asrAverageWer: 0.0229,
    asrMedianWer: 0,
    latencyP50Ms: 7310,
    realTimeFactorP50: 0.84,
    notes: "VoiceDesign model used the bridge's default instruction prompt.",
  },
  {
    modelId: "moss-tts-nano-100m",
    label: "MLX MOSS-TTS Nano 100M",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 96.1,
    asrAverageWer: 0.073,
    asrMedianWer: 0,
    latencyP50Ms: 4420,
    realTimeFactorP50: 0.493,
    notes:
      "Best new MLX-Audio hard-suite result; passed all five prompts using the bundled fallback conditioning prompt.",
    rank: 5,
  },
  {
    modelId: "qwen3-tts-1.7b-base-8bit",
    label: "MLX Qwen3 TTS 1.7B Base 8-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 95.8,
    asrAverageWer: 0.0593,
    asrMedianWer: 0,
    latencyP50Ms: 5925,
    realTimeFactorP50: 0.617,
    notes:
      "Strong new 8-bit Qwen3 result with low ASR WER across all five hard prompts.",
    rank: 6,
  },
  {
    modelId: "qwen3-tts-1.7b-base",
    label: "MLX Qwen3 TTS 1.7B Base",
    status: "tested",
    rank: 7,
    sampleCount: 5,
    passedCases: 5,
    score: 95.6,
    asrAverageWer: 0.0614,
    asrMedianWer: 0,
    latencyP50Ms: 7354,
    realTimeFactorP50: 0.84,
    notes: "Close to the VoiceDesign score without instruction prompting.",
  },
  {
    modelId: "spark-tts-0.5b",
    label: "MLX Spark TTS 0.5B",
    status: "tested",
    rank: 8,
    sampleCount: 5,
    passedCases: 5,
    score: 95,
    asrAverageWer: 0.0887,
    asrMedianWer: 0,
    latencyP50Ms: 7039,
    realTimeFactorP50: 0.78,
    notes: "Passed with the MLX bridge conditioning fallback.",
  },
  {
    modelId: "qwen3-tts-0.6b-4bit",
    label: "MLX Qwen3 TTS 0.6B 4-bit",
    status: "tested",
    rank: 9,
    sampleCount: 5,
    passedCases: 5,
    score: 94.7,
    asrAverageWer: 0.116,
    asrMedianWer: 0,
    latencyP50Ms: 5084,
    realTimeFactorP50: 0.53,
    notes: "Fastest tested Qwen3 MLX variant in the full pass.",
  },
  {
    modelId: "qwen3-tts-0.6b",
    label: "MLX Qwen3 TTS 0.6B",
    status: "tested",
    rank: 10,
    sampleCount: 5,
    passedCases: 5,
    score: 94.6,
    asrAverageWer: 0.1069,
    asrMedianWer: 0,
    latencyP50Ms: 6548,
    realTimeFactorP50: 0.67,
    notes: "Reliable all-case Qwen3 MLX baseline.",
  },
  {
    modelId: "pocket-tts-8bit",
    label: "MLX Pocket TTS 8-bit",
    status: "tested",
    rank: 11,
    sampleCount: 5,
    passedCases: 5,
    score: 94.2,
    asrAverageWer: 0.0593,
    asrMedianWer: 0,
    latencyP50Ms: 10311,
    realTimeFactorP50: 1.04,
    notes: "Best Pocket TTS quantization in this run.",
  },
  {
    modelId: "openvoice",
    label: "OpenVoice",
    status: "tested",
    rank: 12,
    sampleCount: 5,
    passedCases: 5,
    score: 94,
    asrAverageWer: 0.0614,
    asrMedianWer: 0,
    latencyP50Ms: 8708,
    realTimeFactorP50: 1.12,
    notes: "Passed using the current repo managed-runtime worker layout.",
  },
  {
    modelId: "qwen3-tts-0.6b-customvoice",
    label: "MLX Qwen3 TTS 0.6B CustomVoice",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 93.5,
    asrAverageWer: 0.1508,
    asrMedianWer: 0.0345,
    latencyP50Ms: 7715,
    realTimeFactorP50: 0.743,
    notes: "Full-suite CustomVoice pass using the bundled Serena voice.",
    rank: 13,
  },
  {
    modelId: "soprano-80m-4bit",
    label: "MLX Soprano 80M 4-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 93.2,
    asrAverageWer: 0.1892,
    asrMedianWer: 0.2414,
    latencyP50Ms: 2918,
    realTimeFactorP50: 0.365,
    notes:
      "Full-suite Soprano 80M 4-bit pass with the fastest p50 among the new MLX TTS rows.",
    rank: 14,
  },
  {
    modelId: "longcat-audiodit-1b-4bit",
    label: "MLX LongCat AudioDiT 1B 4-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 93.2,
    asrAverageWer: 0.1321,
    asrMedianWer: 0.1379,
    latencyP50Ms: 6640,
    realTimeFactorP50: 0.659,
    notes:
      "Full-suite LongCat pass; strong overall score with moderate latency.",
    rank: 15,
  },
  {
    modelId: "soprano-1-1-80m-bf16",
    label: "MLX Soprano 1.1 80M bf16",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 93.1,
    asrAverageWer: 0.2002,
    asrMedianWer: 0.069,
    latencyP50Ms: 3066,
    realTimeFactorP50: 0.321,
    notes:
      "Full-suite Soprano bf16 pass; slightly lower score than the 4-bit Soprano row.",
    rank: 16,
  },
  {
    modelId: "pocket-tts",
    label: "MLX Pocket TTS",
    status: "tested",
    rank: 17,
    sampleCount: 5,
    passedCases: 5,
    score: 93,
    asrAverageWer: 0.069,
    asrMedianWer: 0.0345,
    latencyP50Ms: 13627,
    realTimeFactorP50: 1.56,
    notes: "Full precision Pocket TTS passed all prompts.",
  },
  {
    modelId: "chatterbox-mlx",
    label: "MLX Chatterbox",
    status: "tested",
    rank: 18,
    sampleCount: 5,
    passedCases: 5,
    score: 92.3,
    asrAverageWer: 0.0956,
    asrMedianWer: 0,
    latencyP50Ms: 9551,
    realTimeFactorP50: 1.45,
    notes: "MLX Chatterbox was faster than the managed Chatterbox variants.",
  },
  {
    modelId: "qwen3-0.6b-base",
    label: "Qwen3 Native 0.6B Base",
    status: "tested",
    rank: 19,
    sampleCount: 5,
    passedCases: 5,
    score: 92,
    asrAverageWer: 0.1759,
    asrMedianWer: 0.24,
    latencyP50Ms: 10061,
    realTimeFactorP50: 1.11,
    notes: "Native runtime installed into the current app runtime directory.",
  },
  {
    modelId: "chatterbox-turbo",
    label: "Chatterbox Turbo",
    status: "tested",
    rank: 20,
    sampleCount: 5,
    passedCases: 5,
    score: 92,
    asrAverageWer: 0.016,
    asrMedianWer: 0,
    latencyP50Ms: 20832,
    realTimeFactorP50: 2.4,
    notes: "Turbo checkpoint layout is now handled by the repo runtime worker.",
  },
  {
    modelId: "xtts-v2",
    label: "XTTS v2",
    status: "tested",
    rank: 21,
    sampleCount: 5,
    passedCases: 5,
    score: 91.9,
    asrAverageWer: 0.0251,
    asrMedianWer: 0,
    latencyP50Ms: 23415,
    realTimeFactorP50: 2.59,
    notes:
      "Passed after testing against the repo runtime worker rather than the older installed worker.",
  },
  {
    modelId: "voxtral-tts-4b",
    label: "MLX Voxtral TTS 4B",
    status: "tested",
    rank: 22,
    sampleCount: 5,
    passedCases: 5,
    score: 91.4,
    asrAverageWer: 0.1774,
    asrMedianWer: 0.069,
    latencyP50Ms: 8710,
    realTimeFactorP50: 1.15,
    notes: "Large MLX model passed all prompts with moderate median latency.",
  },
  {
    modelId: "vibevoice-realtime-0-5b",
    label: "VibeVoice Realtime 0.5B",
    status: "tested",
    rank: 23,
    sampleCount: 5,
    passedCases: 5,
    score: 90.4,
    asrAverageWer: 0.1448,
    asrMedianWer: 0.0345,
    latencyP50Ms: 12929,
    realTimeFactorP50: 1.41,
    notes: "Runner now uses the speech-runtime venv expected by the app.",
  },
  {
    modelId: "dia-1.6b",
    label: "MLX Dia 1.6B",
    status: "tested",
    rank: 24,
    sampleCount: 5,
    passedCases: 5,
    score: 89.7,
    asrAverageWer: 0.0593,
    asrMedianWer: 0,
    latencyP50Ms: 20995,
    realTimeFactorP50: 3.29,
    notes: "Reliable but slower than the leading MLX options.",
  },
  {
    modelId: "melotts-english",
    label: "MLX MeloTTS English",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 89.5,
    asrAverageWer: 0.2601,
    asrMedianWer: 0.1034,
    latencyP50Ms: 5845,
    realTimeFactorP50: 0.707,
    notes:
      "Full-suite MeloTTS pass after adding the g2p_en runtime dependency.",
    rank: 25,
  },
  {
    modelId: "pocket-tts-4bit",
    label: "MLX Pocket TTS 4-bit",
    status: "tested",
    rank: 26,
    sampleCount: 5,
    passedCases: 5,
    score: 89.5,
    asrAverageWer: 0.0883,
    asrMedianWer: 0.069,
    latencyP50Ms: 13372,
    realTimeFactorP50: 1.5,
    notes: "Passed all prompts, behind the 8-bit Pocket TTS variant.",
  },
  {
    modelId: "lfm2-5-audio-1-5b-q4-0",
    label: "LFM2.5 Audio 1.5B GGUF Q4_0",
    status: "tested",
    rank: 27,
    sampleCount: 5,
    passedCases: 4,
    score: 88.7,
    asrAverageWer: 0.0882,
    asrMedianWer: 0.0173,
    latencyP50Ms: 2132,
    realTimeFactorP50: 0.24,
    notes:
      "Fast when it succeeds, but one case exited inside the native Liquid Audio runtime.",
  },
  {
    modelId: "dia-1.6b-4bit",
    label: "MLX Dia 1.6B 4-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 88.7,
    asrAverageWer: 0.0508,
    asrMedianWer: 0.0345,
    latencyP50Ms: 31549,
    realTimeFactorP50: 3.46,
    notes:
      "Full-suite Dia 4-bit pass with low WER but high p50 synthesis latency.",
    rank: 28,
  },
  {
    modelId: "qwen3-0.6b-customvoice",
    label: "Qwen3 Native 0.6B CustomVoice",
    status: "tested",
    rank: 29,
    sampleCount: 5,
    passedCases: 5,
    score: 88.3,
    asrAverageWer: 0.2833,
    asrMedianWer: 0.32,
    latencyP50Ms: 18683,
    realTimeFactorP50: 1.26,
    notes:
      "Partial local install was repaired by downloading the missing Qwen tokenizer files.",
  },
  {
    modelId: "csm-1b",
    label: "MLX CSM 1B",
    status: "tested",
    rank: 30,
    sampleCount: 5,
    passedCases: 5,
    score: 88.2,
    asrAverageWer: 0.2145,
    asrMedianWer: 0.0345,
    latencyP50Ms: 17765,
    realTimeFactorP50: 2.15,
    notes:
      "Passed the full rerun after a transient MLX name-resolution error in an earlier pass.",
  },
  {
    modelId: "bark-small",
    label: "MLX Bark Small",
    status: "tested",
    rank: 31,
    sampleCount: 5,
    passedCases: 5,
    score: 87.8,
    asrAverageWer: 0.1247,
    asrMedianWer: 0.08,
    latencyP50Ms: 38393,
    realTimeFactorP50: 3.22,
    notes:
      "Passed all five cases on isolated rerun after a transient MLX name-resolution failure in the first full pass.",
  },
  {
    modelId: "qwen3-1.7b-customvoice",
    label: "Qwen3 Native 1.7B CustomVoice",
    status: "tested",
    rank: 32,
    sampleCount: 5,
    passedCases: 5,
    score: 87.6,
    asrAverageWer: 0.2231,
    asrMedianWer: 0.2,
    latencyP50Ms: 35019,
    realTimeFactorP50: 2.41,
    notes: "Accurate but much slower than native Qwen3 0.6B.",
  },
  {
    modelId: "chatterbox",
    label: "Chatterbox",
    status: "tested",
    rank: 33,
    sampleCount: 5,
    passedCases: 5,
    score: 87.5,
    asrAverageWer: 0.0342,
    asrMedianWer: 0,
    latencyP50Ms: 29970,
    realTimeFactorP50: 3.46,
    notes:
      "Now uses a bundled fallback voice prompt when no clone profile is selected.",
  },
  {
    modelId: "chatterbox-multilingual",
    label: "Chatterbox Multilingual",
    status: "tested",
    rank: 34,
    sampleCount: 5,
    passedCases: 5,
    score: 83,
    asrAverageWer: 0.1718,
    asrMedianWer: 0,
    latencyP50Ms: 26502,
    realTimeFactorP50: 3.99,
    notes: "Now uses the same bundled fallback prompt path as base Chatterbox.",
  },
  {
    modelId: "tts-sherpa-zh-cn-melo",
    label: "Sherpa Melo Chinese/English",
    status: "tested",
    rank: 35,
    sampleCount: 5,
    passedCases: 5,
    score: 82.9,
    asrAverageWer: 0.5268,
    asrMedianWer: 0.2,
    latencyP50Ms: 4596,
    realTimeFactorP50: 0.47,
    notes:
      "Downloaded and fixed pack handling; the runner no longer passes a missing espeak data dir.",
  },
  {
    modelId: "csm-1b-8bit",
    label: "MLX CSM 1B 8-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 82.7,
    asrAverageWer: 0.466,
    asrMedianWer: 0.25,
    latencyP50Ms: 11463,
    realTimeFactorP50: 1.225,
    notes:
      "Full-suite CSM 8-bit pass using the bundled fallback conditioning prompt.",
    rank: 36,
  },
  {
    modelId: "lfm2-5-audio-1-5b",
    label: "MLX LFM2.5 Audio 1.5B",
    status: "tested",
    rank: 37,
    sampleCount: 5,
    passedCases: 5,
    score: 82.3,
    asrAverageWer: 0.2342,
    asrMedianWer: 0.0345,
    latencyP50Ms: 33289,
    realTimeFactorP50: 3.78,
    notes:
      "Passed all cases, but the MLX path is much slower than the GGUF runner.",
  },
  {
    modelId: "ming-omni-0.5b",
    label: "MLX Ming-omni TTS 0.5B",
    status: "tested",
    rank: 38,
    sampleCount: 5,
    passedCases: 5,
    score: 81.7,
    asrAverageWer: 0.5555,
    asrMedianWer: 0.6667,
    latencyP50Ms: 5043,
    realTimeFactorP50: 0.75,
    notes: "Strong audio-health score with moderate median latency.",
  },
  {
    modelId: "fish-audio-s2-pro",
    label: "MLX Fish Audio S2 Pro",
    status: "tested",
    rank: 39,
    sampleCount: 5,
    passedCases: 5,
    score: 79,
    asrAverageWer: 0.0342,
    asrMedianWer: 0,
    latencyP50Ms: 160734,
    realTimeFactorP50: 18.23,
    notes: "Passed all prompts but was one of the slowest models in the suite.",
  },
  {
    modelId: "voxcpm2-4bit",
    label: "MLX VoxCPM2 4-bit",
    status: "tested",
    rank: 40,
    sampleCount: 5,
    passedCases: 5,
    score: 73.4,
    asrAverageWer: 0.3621,
    asrMedianWer: 0.2273,
    latencyP50Ms: 45450,
    realTimeFactorP50: 5.74,
    notes: "Passed all prompts, but latency is high.",
  },
  {
    modelId: "fish-audio-s2-pro-8bit",
    label: "MLX Fish Audio S2 Pro 8-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 69.1,
    asrAverageWer: 0.8884,
    asrMedianWer: 0.9167,
    latencyP50Ms: 24540,
    realTimeFactorP50: 1.531,
    notes:
      "Full-suite Fish Audio 8-bit pass, but high WER kept it below the leading clone-oriented models.",
    rank: 41,
  },
  {
    modelId: "irodori-tts-500m-v2-4bit",
    label: "MLX Irodori TTS 500M v2 4-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 68,
    asrAverageWer: 0.9193,
    asrMedianWer: 0.9,
    latencyP50Ms: 16533,
    realTimeFactorP50: 1.227,
    notes:
      "Full-suite Irodori pass, but elevated ASR WER kept it low in the hard benchmark.",
    rank: 42,
  },
  {
    modelId: "vibevoice-realtime-0-5b-4bit-mlx",
    label: "MLX VibeVoice Realtime 0.5B 4-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 67.7,
    asrAverageWer: 4.2587,
    asrMedianWer: 1.6897,
    latencyP50Ms: 6885,
    realTimeFactorP50: 0.601,
    notes:
      "Full-suite VibeVoice pass, but ASR round-trip WER was too high for a top hard-suite rank.",
    rank: 43,
  },
  {
    modelId: "kugel-audio-7b",
    label: "MLX KugelAudio 7B",
    status: "tested",
    rank: 44,
    sampleCount: 5,
    passedCases: 1,
    score: 48,
    asrAverageWer: 0,
    asrMedianWer: 0,
    latencyP50Ms: 34103,
    realTimeFactorP50: 17.05,
    notes: "Only one case passed; four cases hit the 300 second timeout.",
  },
  {
    modelId: "spark-tts-0.5b-4-6bit",
    label: "MLX Spark TTS 0.5B 4/6-bit",
    status: "tested",
    sampleCount: 5,
    passedCases: 1,
    score: 42.4,
    asrAverageWer: 0.8182,
    asrMedianWer: 0.8182,
    latencyP50Ms: 4874,
    realTimeFactorP50: 0.402,
    notes:
      "Only one of five hard-suite prompts passed; keep available for manual testing, not recommended as a default.",
    rank: 45,
  },
  {
    modelId: "indextts-1-5",
    label: "MLX IndexTTS 1.5",
    status: "failed",
    sampleCount: 5,
    passedCases: 0,
    notes:
      "Bridge now injects tokenizer_name and the bundled conditioning prompt for IndexTTS; spot-check synthesis works. Full five-case suite re-run pending.",
  },
  {
    modelId: "voxtral-tts-4b-4bit",
    label: "MLX Voxtral TTS 4B 4-bit",
    status: "failed",
    sampleCount: 5,
    passedCases: 0,
    notes:
      "Earlier failure was caused by an incomplete snapshot; the full local snapshot now loads and generates audio. Full five-case suite re-run pending.",
  },
];
