export type TtsEvaluationStatus =
  | "tested"
  | "pending"
  | "download_required"
  | "failed"
  | "blocked";

export interface TtsEvaluationResult {
  modelId: string;
  providerId?: string;
  appModelId?: string;
  label: string;
  status: TtsEvaluationStatus;
  rank?: number;
  sampleCount?: number;
  passedCases?: number;
  score?: number;
  asrAverageWer?: number;
  asrMedianWer?: number;
  latencyP50Ms?: number;
  realTimeFactorP50?: number;
  notes: string;
}

export const TTS_EVALUATION_RUN = {
  generatedAt: "2026-06-15T14:46:48Z",
  suite: "tts_real_world_hard",
  corpus:
    "Five hard readback prompts covering casual text, long meeting summary, code and symbols, numbers/dates, and multilingual Spanish text. All rows were synthesized through the installed Vox Jot app local API using canonical provider/model IDs with ASR round-trip scoring enabled.",
  limitations:
    "Scores combine synthesis success, local ASR round-trip WER, real-time factor, and generated-WAV health checks. Human MOS ratings and far-field playback capture are not included; app-path failures are left visible as failed rows rather than ranked leaderboard entries. Orpheus and ZONOS2 rows are from the 2026-06-15 installed-app API hard-suite run; KittenTTS (nano/micro/mini) and MisoTTS (8-bit/bf16) rows are from the 2026-06-07 app-API hard-suite run; the remaining rows are from the 2026-05-21 run under the identical suite.",
  metricGuide: [
    "Rank: #1 is best for this installed-app suite.",
    "Score and pass: higher is better.",
    "ASR WER: lower is better.",
    "p50 latency: lower is faster.",
    "RTF: lower is faster; below 1.00 is faster than real time.",
  ],
  reportPath:
    "output/tts-model-eval/app-full-2026-06-15-orpheus-zonos2/tts-eval-summary.json",
};

export const TTS_EVALUATION_RESULTS: TtsEvaluationResult[] = [
  {
    modelId: "system-default",
    providerId: "system_builtin",
    appModelId: "system-default",
    label: "Apple System Voice",
    status: "tested",
    rank: 1,
    sampleCount: 5,
    passedCases: 5,
    score: 98.6,
    asrAverageWer: 0.0389,
    asrMedianWer: 0.0455,
    latencyP50Ms: 507,
    realTimeFactorP50: 0.047,
    notes:
      "Full installed-app API hard-suite run through system_builtin/system-default; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "supertonic-3",
    providerId: "supertonic",
    appModelId: "supertonic-3",
    label: "Supertonic 3",
    status: "tested",
    rank: 2,
    sampleCount: 5,
    passedCases: 5,
    score: 98.6,
    asrAverageWer: 0.032,
    asrMedianWer: 0,
    latencyP50Ms: 1276,
    realTimeFactorP50: 0.11,
    notes:
      "Full installed-app API hard-suite run through supertonic/supertonic-3; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-it-it-paola-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-it-it-paola-medium",
    label: "Sherpa Paola Medium",
    status: "tested",
    rank: 3,
    sampleCount: 5,
    passedCases: 5,
    score: 98,
    asrAverageWer: 0.0577,
    asrMedianWer: 0.069,
    latencyP50Ms: 741,
    realTimeFactorP50: 0.089,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-it-it-paola-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-fr-fr-siwis-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-fr-fr-siwis-medium",
    label: "Sherpa Siwis Medium",
    status: "tested",
    rank: 4,
    sampleCount: 5,
    passedCases: 5,
    score: 98,
    asrAverageWer: 0.0577,
    asrMedianWer: 0.069,
    latencyP50Ms: 730,
    realTimeFactorP50: 0.088,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-fr-fr-siwis-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kokoro-82m",
    providerId: "mlx_kokoro",
    appModelId: "kokoro-82m",
    label: "MLX Kokoro 82M",
    status: "tested",
    rank: 5,
    sampleCount: 5,
    passedCases: 5,
    score: 97.7,
    asrAverageWer: 0.0229,
    asrMedianWer: 0,
    latencyP50Ms: 2712,
    realTimeFactorP50: 0.261,
    notes:
      "Full installed-app API hard-suite run through mlx_kokoro/kokoro-82m; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-en-us-lessac-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-en-us-lessac-medium",
    label: "Sherpa Lessac Medium",
    status: "tested",
    rank: 6,
    sampleCount: 5,
    passedCases: 5,
    score: 97.5,
    asrAverageWer: 0.07,
    asrMedianWer: 0.0455,
    latencyP50Ms: 745,
    realTimeFactorP50: 0.089,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-en-us-lessac-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-en-us-amy-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-en-us-amy-medium",
    label: "Sherpa Amy Medium",
    status: "tested",
    rank: 7,
    sampleCount: 5,
    passedCases: 5,
    score: 97.4,
    asrAverageWer: 0.0729,
    asrMedianWer: 0.0455,
    latencyP50Ms: 896,
    realTimeFactorP50: 0.123,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-en-us-amy-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-pt-br-faber-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-pt-br-faber-medium",
    label: "Sherpa Faber Medium",
    status: "tested",
    rank: 8,
    sampleCount: 5,
    passedCases: 5,
    score: 97.3,
    asrAverageWer: 0.0809,
    asrMedianWer: 0.0455,
    latencyP50Ms: 744,
    realTimeFactorP50: 0.085,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-pt-br-faber-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-de-de-thorsten-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-de-de-thorsten-medium",
    label: "Sherpa Thorsten Medium",
    status: "tested",
    rank: 9,
    sampleCount: 5,
    passedCases: 5,
    score: 97.2,
    asrAverageWer: 0.0835,
    asrMedianWer: 0.069,
    latencyP50Ms: 735,
    realTimeFactorP50: 0.088,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-de-de-thorsten-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-es-es-davefx-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-es-es-davefx-medium",
    label: "Sherpa DaveFX Medium",
    status: "tested",
    rank: 10,
    sampleCount: 5,
    passedCases: 5,
    score: 97,
    asrAverageWer: 0.0911,
    asrMedianWer: 0.069,
    latencyP50Ms: 766,
    realTimeFactorP50: 0.096,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-es-es-davefx-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "moss-tts-nano-100m",
    providerId: "mlx_moss_tts",
    appModelId: "moss-tts-nano-100m",
    label: "MLX MOSS-TTS Nano 100M",
    status: "tested",
    rank: 11,
    sampleCount: 5,
    passedCases: 5,
    score: 96.7,
    asrAverageWer: 0.048,
    asrMedianWer: 0,
    latencyP50Ms: 4573,
    realTimeFactorP50: 0.51,
    notes:
      "Full installed-app API hard-suite run through mlx_moss_tts/moss-tts-nano-100m; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "pocket-tts",
    providerId: "mlx_pocket_tts",
    appModelId: "pocket-tts",
    label: "MLX Pocket TTS",
    status: "tested",
    rank: 12,
    sampleCount: 5,
    passedCases: 5,
    score: 96.4,
    asrAverageWer: 0.0857,
    asrMedianWer: 0.0345,
    latencyP50Ms: 2957,
    realTimeFactorP50: 0.336,
    notes:
      "Full installed-app API hard-suite run through mlx_pocket_tts/pocket-tts; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kitten-tts-micro-0.8",
    providerId: "mlx_kitten_tts",
    appModelId: "kitten-tts-micro-0.8",
    label: "KittenTTS Micro 0.8",
    status: "tested",
    rank: 13,
    sampleCount: 5,
    passedCases: 5,
    score: 95.9,
    asrAverageWer: 0.1243,
    asrMedianWer: 0.1034,
    latencyP50Ms: 1771,
    realTimeFactorP50: 0.159,
    notes:
      "Full installed-app API hard-suite run through mlx_kitten_tts/kitten-tts-micro-0.8; 5/5 cases generated with ASR round-trip scoring (2026-06-07).",
  },
  {
    modelId: "omnivoice",
    providerId: "mlx_omnivoice",
    appModelId: "omnivoice",
    label: "MLX OmniVoice",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 95.6,
    asrAverageWer: 0.0614,
    latencyP50Ms: 6685,
    realTimeFactorP50: 0.658,
    notes:
      "Full installed-app API hard-suite run through mlx_omnivoice/omnivoice; 5/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0,
    rank: 14,
  },
  {
    modelId: "pocket-tts-4bit",
    providerId: "mlx_pocket_tts",
    appModelId: "pocket-tts-4bit",
    label: "MLX Pocket TTS 4-bit",
    status: "tested",
    rank: 15,
    sampleCount: 5,
    passedCases: 5,
    score: 95.5,
    asrAverageWer: 0.1152,
    asrMedianWer: 0.0833,
    latencyP50Ms: 2655,
    realTimeFactorP50: 0.305,
    notes:
      "Full installed-app API hard-suite run through mlx_pocket_tts/pocket-tts-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "pocket-tts-8bit",
    providerId: "mlx_pocket_tts",
    appModelId: "pocket-tts-8bit",
    label: "MLX Pocket TTS 8-bit",
    status: "tested",
    rank: 16,
    sampleCount: 5,
    passedCases: 5,
    score: 95.4,
    asrAverageWer: 0.1175,
    asrMedianWer: 0.0345,
    latencyP50Ms: 2697,
    realTimeFactorP50: 0.298,
    notes:
      "Full installed-app API hard-suite run through mlx_pocket_tts/pocket-tts-8bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-tts-1.7b-base-8bit",
    providerId: "mlx_qwen3tts",
    appModelId: "qwen3-tts-1.7b-base-8bit",
    label: "MLX Qwen3 TTS 1.7B Base 8-bit",
    status: "tested",
    rank: 17,
    sampleCount: 5,
    passedCases: 5,
    score: 95.4,
    asrAverageWer: 0.0502,
    asrMedianWer: 0,
    latencyP50Ms: 6086,
    realTimeFactorP50: 0.793,
    notes:
      "Full installed-app API hard-suite run through mlx_qwen3tts/qwen3-tts-1.7b-base-8bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-tts-0.6b-4bit",
    providerId: "mlx_qwen3tts",
    appModelId: "qwen3-tts-0.6b-4bit",
    label: "MLX Qwen3 TTS 0.6B 4-bit",
    status: "tested",
    rank: 18,
    sampleCount: 5,
    passedCases: 5,
    score: 95.2,
    asrAverageWer: 0.0956,
    asrMedianWer: 0,
    latencyP50Ms: 4744,
    realTimeFactorP50: 0.482,
    notes:
      "Full installed-app API hard-suite run through mlx_qwen3tts/qwen3-tts-0.6b-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kokoro-82m-v1.0",
    providerId: "kokoro",
    appModelId: "kokoro-82m-v1.0",
    label: "Kokoro 82M",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 95.1,
    asrAverageWer: 0.0411,
    latencyP50Ms: 1771,
    realTimeFactorP50: 0.193,
    notes:
      "Full installed-app API hard-suite run through kokoro/kokoro-82m-v1.0; 5/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0,
    rank: 19,
  },
  {
    modelId: "voxtral-tts-4b-4bit",
    providerId: "mlx_voxtral_tts",
    appModelId: "voxtral-tts-4b-4bit",
    label: "MLX Voxtral TTS 4B 4-bit",
    status: "tested",
    rank: 20,
    sampleCount: 5,
    passedCases: 5,
    score: 95.1,
    asrAverageWer: 0.0956,
    asrMedianWer: 0,
    latencyP50Ms: 6859,
    realTimeFactorP50: 0.68,
    notes:
      "Full installed-app API hard-suite run through mlx_voxtral_tts/voxtral-tts-4b-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kitten-tts-mini-0.8",
    providerId: "mlx_kitten_tts",
    appModelId: "kitten-tts-mini-0.8",
    label: "KittenTTS Mini 0.8",
    status: "tested",
    rank: 21,
    sampleCount: 5,
    passedCases: 5,
    score: 94.6,
    asrAverageWer: 0.1617,
    asrMedianWer: 0.2,
    latencyP50Ms: 1768,
    realTimeFactorP50: 0.203,
    notes:
      "Full installed-app API hard-suite run through mlx_kitten_tts/kitten-tts-mini-0.8; 5/5 cases generated with ASR round-trip scoring (2026-06-07).",
  },
  {
    modelId: "tts-sherpa-en-gb-alan-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-en-gb-alan-medium",
    label: "Sherpa Alan Medium",
    status: "tested",
    rank: 22,
    sampleCount: 5,
    passedCases: 5,
    score: 94.5,
    asrAverageWer: 0.1755,
    asrMedianWer: 0.04,
    latencyP50Ms: 907,
    realTimeFactorP50: 0.084,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-en-gb-alan-medium; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-tts-1.7b",
    providerId: "mlx_qwen3tts",
    appModelId: "qwen3-tts-1.7b",
    label: "MLX Qwen3 TTS 1.7B VoiceDesign",
    status: "tested",
    rank: 23,
    sampleCount: 5,
    passedCases: 5,
    score: 94.3,
    asrAverageWer: 0.1093,
    asrMedianWer: 0.069,
    latencyP50Ms: 7984,
    realTimeFactorP50: 0.898,
    notes:
      "Full installed-app API hard-suite run through mlx_qwen3tts/qwen3-tts-1.7b; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox-mlx",
    providerId: "mlx_chatterbox",
    appModelId: "chatterbox",
    label: "MLX Chatterbox",
    status: "tested",
    rank: 24,
    sampleCount: 5,
    passedCases: 5,
    score: 94.2,
    asrAverageWer: 0.0941,
    asrMedianWer: 0.069,
    latencyP50Ms: 7428,
    realTimeFactorP50: 0.919,
    notes:
      "Full installed-app API hard-suite run through mlx_chatterbox/chatterbox; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "openvoice",
    providerId: "openvoice",
    appModelId: "openvoice",
    label: "OpenVoice",
    status: "tested",
    rank: 25,
    sampleCount: 5,
    passedCases: 5,
    score: 94.2,
    asrAverageWer: 0.0774,
    asrMedianWer: 0,
    latencyP50Ms: 1785,
    realTimeFactorP50: 0.202,
    notes:
      "Full installed-app API hard-suite run through openvoice/openvoice; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "longcat-audiodit-3-5b-4bit",
    providerId: "mlx_longcat_audiodit",
    appModelId: "longcat-audiodit-3-5b-4bit",
    label: "MLX LongCat AudioDiT 3.5B 4-bit",
    status: "tested",
    rank: 26,
    sampleCount: 5,
    passedCases: 5,
    score: 94.1,
    asrAverageWer: 0.085,
    asrMedianWer: 0.069,
    latencyP50Ms: 9926,
    realTimeFactorP50: 0.986,
    notes:
      "Full installed-app API hard-suite run through mlx_longcat_audiodit/longcat-audiodit-3-5b-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "longcat-audiodit-1b-4bit",
    providerId: "mlx_longcat_audiodit",
    appModelId: "longcat-audiodit-1b-4bit",
    label: "MLX LongCat AudioDiT 1B 4-bit",
    status: "tested",
    rank: 27,
    sampleCount: 5,
    passedCases: 5,
    score: 93.7,
    asrAverageWer: 0.1321,
    asrMedianWer: 0.1379,
    latencyP50Ms: 6045,
    realTimeFactorP50: 0.617,
    notes:
      "Full installed-app API hard-suite run through mlx_longcat_audiodit/longcat-audiodit-1b-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "longcat-audiodit-1b-bf16",
    providerId: "mlx_longcat_audiodit",
    appModelId: "longcat-audiodit-1b-bf16",
    label: "MLX LongCat AudioDiT 1B bf16",
    status: "tested",
    rank: 28,
    sampleCount: 5,
    passedCases: 5,
    score: 93.2,
    asrAverageWer: 0.1419,
    asrMedianWer: 0.1034,
    latencyP50Ms: 6551,
    realTimeFactorP50: 0.651,
    notes:
      "Full installed-app API hard-suite run through mlx_longcat_audiodit/longcat-audiodit-1b-bf16; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "spark-tts-0.5b",
    providerId: "mlx_spark",
    appModelId: "spark-tts-0.5b",
    label: "MLX Spark TTS 0.5B",
    status: "tested",
    rank: 29,
    sampleCount: 5,
    passedCases: 5,
    score: 92.4,
    asrAverageWer: 0.179,
    asrMedianWer: 0.069,
    latencyP50Ms: 6385,
    realTimeFactorP50: 0.683,
    notes:
      "Full installed-app API hard-suite run through mlx_spark/spark-tts-0.5b; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "orpheus-3b-0.1-ft-4bit",
    providerId: "mlx_orpheus",
    appModelId: "orpheus-3b-0.1-ft-4bit",
    label: "MLX Orpheus 3B 4-bit",
    status: "tested",
    rank: 30,
    sampleCount: 5,
    passedCases: 5,
    score: 92.0,
    asrAverageWer: 0.1419,
    asrMedianWer: 0.1034,
    latencyP50Ms: 13439,
    realTimeFactorP50: 1.419,
    notes:
      "Full installed-app API hard-suite run through mlx_orpheus/orpheus-3b-0.1-ft-4bit; 5/5 cases generated with ASR round-trip scoring (2026-06-15).",
  },
  {
    modelId: "csm-1b-8bit",
    providerId: "mlx_csm",
    appModelId: "csm-1b-8bit",
    label: "MLX CSM 1B 8-bit",
    status: "tested",
    rank: 31,
    sampleCount: 5,
    passedCases: 5,
    score: 91.9,
    asrAverageWer: 0.169,
    asrMedianWer: 0.0345,
    latencyP50Ms: 8053,
    realTimeFactorP50: 0.979,
    notes:
      "Full installed-app API hard-suite run through mlx_csm/csm-1b-8bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "soprano-80m-4bit",
    providerId: "mlx_soprano",
    appModelId: "soprano-80m-4bit",
    label: "MLX Soprano 80M 4-bit",
    status: "tested",
    rank: 32,
    sampleCount: 5,
    passedCases: 5,
    score: 91.5,
    asrAverageWer: 0.2434,
    asrMedianWer: 0.08,
    latencyP50Ms: 2907,
    realTimeFactorP50: 0.332,
    notes:
      "Full installed-app API hard-suite run through mlx_soprano/soprano-80m-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "soprano-1-1-80m-bf16",
    providerId: "mlx_soprano",
    appModelId: "soprano-1-1-80m-bf16",
    label: "MLX Soprano 1.1 80M bf16",
    status: "tested",
    rank: 33,
    sampleCount: 5,
    passedCases: 5,
    score: 91.2,
    asrAverageWer: 0.2661,
    asrMedianWer: 0.1034,
    latencyP50Ms: 2895,
    realTimeFactorP50: 0.353,
    notes:
      "Full installed-app API hard-suite run through mlx_soprano/soprano-1-1-80m-bf16; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kitten-tts-nano-0.8",
    providerId: "mlx_kitten_tts",
    appModelId: "kitten-tts-nano-0.8",
    label: "KittenTTS Nano 0.8",
    status: "tested",
    rank: 34,
    sampleCount: 5,
    passedCases: 5,
    score: 91.1,
    asrAverageWer: 0.1275,
    asrMedianWer: 0.1,
    latencyP50Ms: 1367,
    realTimeFactorP50: 0.123,
    notes:
      "Full installed-app API hard-suite run through mlx_kitten_tts/kitten-tts-nano-0.8; 5/5 cases generated with ASR round-trip scoring (2026-06-07).",
  },
  {
    modelId: "melotts-english",
    providerId: "mlx_melotts",
    appModelId: "melotts-english",
    label: "MLX MeloTTS English",
    status: "tested",
    rank: 35,
    sampleCount: 5,
    passedCases: 5,
    score: 91,
    asrAverageWer: 0.2252,
    asrMedianWer: 0.1034,
    latencyP50Ms: 4593,
    realTimeFactorP50: 0.576,
    notes:
      "Full installed-app API hard-suite run through mlx_melotts/melotts-english; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "vibevoice-realtime-0-5b",
    providerId: "vibevoice",
    appModelId: "vibevoice-realtime-0-5b",
    label: "VibeVoice Realtime 0.5B",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 90.9,
    asrAverageWer: 0.1108,
    latencyP50Ms: 14428,
    realTimeFactorP50: 1.387,
    notes:
      "Full installed-app API hard-suite run through vibevoice/vibevoice-realtime-0-5b; 5/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0.069,
    rank: 36,
  },
  {
    modelId: "lfm2-5-audio-1-5b",
    providerId: "mlx_lfm_audio",
    appModelId: "lfm2-5-audio-1-5b",
    label: "MLX LFM2.5 Audio 1.5B",
    status: "tested",
    rank: 37,
    sampleCount: 5,
    passedCases: 5,
    score: 90.8,
    asrAverageWer: 0.2338,
    asrMedianWer: 0.1,
    latencyP50Ms: 6172,
    realTimeFactorP50: 0.742,
    notes:
      "Full installed-app API hard-suite run through mlx_lfm_audio/lfm2-5-audio-1-5b; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox-turbo",
    providerId: "chatterbox",
    appModelId: "chatterbox-turbo",
    label: "Chatterbox Turbo",
    status: "tested",
    rank: 38,
    sampleCount: 5,
    passedCases: 5,
    score: 89.6,
    asrAverageWer: 0.1249,
    asrMedianWer: 0.1667,
    latencyP50Ms: 9873,
    realTimeFactorP50: 0.835,
    notes:
      "Full installed-app API hard-suite run through chatterbox/chatterbox-turbo; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "csm-1b",
    providerId: "mlx_csm",
    appModelId: "csm-1b",
    label: "MLX CSM 1B",
    status: "tested",
    rank: 39,
    sampleCount: 5,
    passedCases: 5,
    score: 89.5,
    asrAverageWer: 0.1948,
    asrMedianWer: 0.0345,
    latencyP50Ms: 13400,
    realTimeFactorP50: 1.595,
    notes:
      "Full installed-app API hard-suite run through mlx_csm/csm-1b; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "dia-1.6b-4bit",
    providerId: "mlx_dia",
    appModelId: "dia-1.6b-4bit",
    label: "MLX Dia 1.6B 4-bit",
    status: "tested",
    rank: 40,
    sampleCount: 5,
    passedCases: 5,
    score: 89.1,
    asrAverageWer: 0.0702,
    asrMedianWer: 0.069,
    latencyP50Ms: 19585,
    realTimeFactorP50: 3.231,
    notes:
      "Full installed-app API hard-suite run through mlx_dia/dia-1.6b-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-0.6b-base",
    providerId: "qwen3_native",
    appModelId: "qwen3-0.6b-base",
    label: "Qwen3 Native 0.6B Base",
    status: "tested",
    rank: 41,
    sampleCount: 5,
    passedCases: 5,
    score: 88.6,
    asrAverageWer: 0.2568,
    asrMedianWer: 0.25,
    latencyP50Ms: 12096,
    realTimeFactorP50: 1.338,
    notes:
      "Full installed-app API hard-suite run through qwen3_native/qwen3-0.6b-base; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "voxtral-tts-4b",
    providerId: "mlx_voxtral_tts",
    appModelId: "voxtral-tts-4b",
    label: "MLX Voxtral TTS 4B",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 88.2,
    asrAverageWer: 0.1795,
    latencyP50Ms: 20200,
    realTimeFactorP50: 2.316,
    notes:
      "Full installed-app API hard-suite run through mlx_voxtral_tts/voxtral-tts-4b; 5/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0.0833,
    rank: 42,
  },
  {
    modelId: "dia-1.6b",
    providerId: "mlx_dia",
    appModelId: "dia-1.6b",
    label: "MLX Dia 1.6B",
    status: "tested",
    rank: 43,
    sampleCount: 5,
    passedCases: 5,
    score: 88.1,
    asrAverageWer: 0.1542,
    asrMedianWer: 0.0345,
    latencyP50Ms: 24582,
    realTimeFactorP50: 2.946,
    notes:
      "Full installed-app API hard-suite run through mlx_dia/dia-1.6b; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "lfm2-5-audio-1-5b-q4-0",
    providerId: "lfm_audio_gguf",
    appModelId: "lfm2-5-audio-1-5b-q4-0",
    label: "LFM2.5 Audio 1.5B GGUF Q4_0",
    status: "tested",
    sampleCount: 5,
    passedCases: 4,
    score: 87,
    asrAverageWer: 0.1404,
    latencyP50Ms: 2327,
    realTimeFactorP50: 0.258,
    notes:
      "Full installed-app API hard-suite run through lfm_audio_gguf/lfm2-5-audio-1-5b-q4-0; 4/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0.0761,
    rank: 44,
  },
  {
    modelId: "higgs-audio-v2-3b-q8",
    providerId: "mlx_higgs_audio",
    appModelId: "higgs-audio-v2-3b-q8",
    label: "MLX Higgs Audio v2 3B q8",
    status: "tested",
    rank: 45,
    sampleCount: 5,
    passedCases: 5,
    score: 86.2,
    asrAverageWer: 0.348,
    asrMedianWer: 0.1034,
    latencyP50Ms: 15562,
    realTimeFactorP50: 0.901,
    notes:
      "Full installed-app API hard-suite run through mlx_higgs_audio/higgs-audio-v2-3b-q8; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "outetts-1b-4bit",
    providerId: "mlx_oute",
    appModelId: "outetts-1b-4bit",
    label: "MLX Llama OuteTTS 1B 4-bit",
    status: "tested",
    rank: 46,
    sampleCount: 5,
    passedCases: 5,
    score: 85.4,
    asrAverageWer: 0.335,
    asrMedianWer: 0.44,
    latencyP50Ms: 11377,
    realTimeFactorP50: 1.684,
    notes:
      "Full installed-app API hard-suite run through mlx_oute/outetts-1b-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox",
    providerId: "chatterbox",
    appModelId: "chatterbox",
    label: "Chatterbox",
    status: "tested",
    rank: 47,
    sampleCount: 5,
    passedCases: 5,
    score: 84.7,
    asrAverageWer: 0.1321,
    asrMedianWer: 0.1379,
    latencyP50Ms: 17575,
    realTimeFactorP50: 1.8,
    notes:
      "Full installed-app API hard-suite run through chatterbox/chatterbox; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "zonos2",
    providerId: "mlx_zonos2",
    appModelId: "zonos2",
    label: "MLX ZONOS2",
    status: "tested",
    rank: 48,
    sampleCount: 5,
    passedCases: 4,
    score: 84.4,
    asrAverageWer: 0.0568,
    asrMedianWer: 0.0,
    latencyP50Ms: 25619,
    realTimeFactorP50: 2.031,
    notes:
      "Full installed-app API hard-suite run through mlx_zonos2/zonos2; 4/5 cases generated with ASR round-trip scoring. The numbers/dates case produced effectively silent audio and is captured in the report (2026-06-15).",
  },
  {
    modelId: "vibevoice-realtime-0-5b-4bit-mlx",
    providerId: "mlx_vibevoice",
    appModelId: "vibevoice-realtime-0-5b-4bit-mlx",
    label: "MLX VibeVoice Realtime 0.5B 4-bit",
    status: "tested",
    rank: 49,
    sampleCount: 5,
    passedCases: 5,
    score: 83.9,
    asrAverageWer: 0.4718,
    asrMedianWer: 0.2759,
    latencyP50Ms: 4252,
    realTimeFactorP50: 0.517,
    notes:
      "Full installed-app API hard-suite run through mlx_vibevoice/vibevoice-realtime-0-5b-4bit-mlx; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "voxcpm2-bf16",
    providerId: "mlx_voxcpm",
    appModelId: "voxcpm2-bf16",
    label: "MLX VoxCPM2 bf16",
    status: "tested",
    rank: 50,
    sampleCount: 5,
    passedCases: 5,
    score: 82.5,
    asrAverageWer: 0.3988,
    asrMedianWer: 0.1034,
    latencyP50Ms: 13005,
    realTimeFactorP50: 1.563,
    notes:
      "Full installed-app API hard-suite run through mlx_voxcpm/voxcpm2-bf16; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "voxcpm2-4bit",
    providerId: "mlx_voxcpm",
    appModelId: "voxcpm2-4bit",
    label: "MLX VoxCPM2 4-bit",
    status: "tested",
    rank: 51,
    sampleCount: 5,
    passedCases: 5,
    score: 80.6,
    asrAverageWer: 0.5179,
    asrMedianWer: 0.3333,
    latencyP50Ms: 9563,
    realTimeFactorP50: 1.172,
    notes:
      "Full installed-app API hard-suite run through mlx_voxcpm/voxcpm2-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "voxcpm2-8bit",
    providerId: "mlx_voxcpm",
    appModelId: "voxcpm2-8bit",
    label: "MLX VoxCPM2 8-bit",
    status: "tested",
    rank: 52,
    sampleCount: 5,
    passedCases: 5,
    score: 80.5,
    asrAverageWer: 0.5009,
    asrMedianWer: 0.28,
    latencyP50Ms: 9659,
    realTimeFactorP50: 1.207,
    notes:
      "Full installed-app API hard-suite run through mlx_voxcpm/voxcpm2-8bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "indextts-1-5",
    providerId: "mlx_indextts",
    appModelId: "indextts-1-5",
    label: "MLX IndexTTS 1.5",
    status: "tested",
    rank: 53,
    sampleCount: 5,
    passedCases: 5,
    score: 80.4,
    asrAverageWer: 0.5014,
    asrMedianWer: 0.4,
    latencyP50Ms: 9253,
    realTimeFactorP50: 1.278,
    notes:
      "Full installed-app API hard-suite run through mlx_indextts/indextts-1-5; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-zh-cn-melo",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-zh-cn-melo",
    label: "Sherpa Melo Chinese/English",
    status: "tested",
    rank: 54,
    sampleCount: 5,
    passedCases: 5,
    score: 79.8,
    asrAverageWer: 0.6304,
    asrMedianWer: 0.36,
    latencyP50Ms: 4401,
    realTimeFactorP50: 0.477,
    notes:
      "Full installed-app API hard-suite run through sherpa_pack/tts-sherpa-zh-cn-melo; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "miso-tts-bf16",
    providerId: "mlx_miso_tts",
    appModelId: "miso-tts-bf16",
    label: "MisoTTS bf16",
    status: "tested",
    rank: 55,
    sampleCount: 5,
    passedCases: 5,
    score: 79.8,
    asrAverageWer: 0.4171,
    asrMedianWer: 0.1379,
    latencyP50Ms: 29672,
    realTimeFactorP50: 3.029,
    notes:
      "Full installed-app API hard-suite run through mlx_miso_tts/miso-tts-bf16; 5/5 cases generated with ASR round-trip scoring (2026-06-07).",
  },
  {
    modelId: "miso-tts-8bit",
    providerId: "mlx_miso_tts",
    appModelId: "miso-tts-8bit",
    label: "MisoTTS 8-bit",
    status: "tested",
    rank: 56,
    sampleCount: 5,
    passedCases: 5,
    score: 78.9,
    asrAverageWer: 0.4683,
    asrMedianWer: 0.069,
    latencyP50Ms: 19839,
    realTimeFactorP50: 2.29,
    notes:
      "Full installed-app API hard-suite run through mlx_miso_tts/miso-tts-8bit; 5/5 cases generated with ASR round-trip scoring (2026-06-07).",
  },
  {
    modelId: "bark-small",
    providerId: "mlx_bark",
    appModelId: "bark-small",
    label: "MLX Bark Small",
    status: "tested",
    rank: 57,
    sampleCount: 5,
    passedCases: 5,
    score: 78.7,
    asrAverageWer: 0.1656,
    asrMedianWer: 0.1,
    latencyP50Ms: 40080,
    realTimeFactorP50: 3.07,
    notes:
      "Full installed-app API hard-suite run through mlx_bark/bark-small; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kugel-audio-7b",
    providerId: "mlx_kugel",
    appModelId: "kugel-audio-7b",
    label: "MLX KugelAudio 7B",
    status: "tested",
    sampleCount: 5,
    passedCases: 5,
    score: 76.5,
    asrAverageWer: 0.116,
    latencyP50Ms: 96176,
    realTimeFactorP50: 12.147,
    notes:
      "Full installed-app API hard-suite run through mlx_kugel/kugel-audio-7b; 5/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0,
    rank: 58,
  },
  {
    modelId: "ming-omni-0.5b",
    providerId: "mlx_ming_omni",
    appModelId: "ming-omni-0.5b",
    label: "MLX Ming-omni TTS 0.5B",
    status: "tested",
    rank: 59,
    sampleCount: 5,
    passedCases: 5,
    score: 68.9,
    asrAverageWer: 3.2084,
    asrMedianWer: 1.2,
    latencyP50Ms: 6290,
    realTimeFactorP50: 0.457,
    notes:
      "Full installed-app API hard-suite run through mlx_ming_omni/ming-omni-0.5b; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "irodori-tts-500m-v2-4bit",
    providerId: "mlx_irodori_tts",
    appModelId: "irodori-tts-500m-v2-4bit",
    label: "MLX Irodori TTS 500M v2 4-bit",
    status: "tested",
    rank: 60,
    sampleCount: 5,
    passedCases: 5,
    score: 68.5,
    asrAverageWer: 0.9193,
    asrMedianWer: 0.9,
    latencyP50Ms: 14894,
    realTimeFactorP50: 0.963,
    notes:
      "Full installed-app API hard-suite run through mlx_irodori_tts/irodori-tts-500m-v2-4bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox-multilingual",
    providerId: "chatterbox",
    appModelId: "chatterbox-multilingual",
    label: "Chatterbox Multilingual",
    status: "tested",
    rank: 61,
    sampleCount: 5,
    passedCases: 5,
    score: 68.2,
    asrAverageWer: 0.4842,
    asrMedianWer: 0.5172,
    latencyP50Ms: 9703,
    realTimeFactorP50: 2.213,
    notes:
      "Full installed-app API hard-suite run through chatterbox/chatterbox-multilingual; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "fish-audio-s2-pro-8bit",
    providerId: "mlx_fish_audio",
    appModelId: "fish-audio-s2-pro-8bit",
    label: "MLX Fish Audio S2 Pro 8-bit",
    status: "tested",
    rank: 62,
    sampleCount: 5,
    passedCases: 5,
    score: 67.3,
    asrAverageWer: 0.9764,
    asrMedianWer: 1,
    latencyP50Ms: 20794,
    realTimeFactorP50: 1.264,
    notes:
      "Full installed-app API hard-suite run through mlx_fish_audio/fish-audio-s2-pro-8bit; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "higgs-audio-v2-3b-q6",
    providerId: "mlx_higgs_audio",
    appModelId: "higgs-audio-v2-3b-q6",
    label: "MLX Higgs Audio v2 3B q6",
    status: "tested",
    rank: 63,
    sampleCount: 5,
    passedCases: 5,
    score: 67.1,
    asrAverageWer: 1.7935,
    asrMedianWer: 0.7931,
    latencyP50Ms: 10567,
    realTimeFactorP50: 0.805,
    notes:
      "Full installed-app API hard-suite run through mlx_higgs_audio/higgs-audio-v2-3b-q6; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "fish-audio-s2-pro",
    providerId: "mlx_fish_audio",
    appModelId: "fish-audio-s2-pro",
    label: "MLX Fish Audio S2 Pro",
    status: "tested",
    rank: 64,
    sampleCount: 5,
    passedCases: 5,
    score: 64.7,
    asrAverageWer: 1.2524,
    asrMedianWer: 0.9655,
    latencyP50Ms: 34863,
    realTimeFactorP50: 2.026,
    notes:
      "Full installed-app API hard-suite run through mlx_fish_audio/fish-audio-s2-pro; 5/5 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "spark-tts-0.5b-4-6bit",
    providerId: "mlx_spark",
    appModelId: "spark-tts-0.5b-4-6bit",
    label: "MLX Spark TTS 0.5B 4/6-bit",
    status: "tested",
    rank: 65,
    sampleCount: 5,
    passedCases: 2,
    score: 61.9,
    asrAverageWer: 0.375,
    asrMedianWer: 0.375,
    latencyP50Ms: 4308,
    realTimeFactorP50: 1.141,
    notes:
      "Full installed-app API hard-suite run through mlx_spark/spark-tts-0.5b-4-6bit; 2/5 cases generated with ASR round-trip scoring. Failed cases are captured in the report and the row is ranked from the completed full-suite result.",
  },
  {
    modelId: "xtts-v2",
    providerId: "xtts",
    appModelId: "xtts-v2",
    label: "XTTS v2",
    status: "tested",
    sampleCount: 5,
    passedCases: 4,
    score: 60.5,
    asrAverageWer: 0.8958,
    latencyP50Ms: 4804,
    realTimeFactorP50: 0.455,
    notes:
      "Full installed-app API hard-suite run through xtts/xtts-v2; 4/5 cases generated with ASR round-trip scoring.",
    asrMedianWer: 0.5,
    rank: 66,
  },
];

export function getTtsEvaluationResult(
  modelId: string,
): TtsEvaluationResult | undefined {
  return TTS_EVALUATION_RESULTS.find((result) => result.modelId === modelId);
}
