export type TtsStyleEvaluationStatus = "tested" | "failed" | "blocked";

export interface TtsStyleEvaluationResult {
  modelId: string;
  providerId?: string;
  appModelId?: string;
  label: string;
  status: TtsStyleEvaluationStatus;
  rank?: number;
  sampleCount?: number;
  passedCases?: number;
  score?: number;
  styleProxy?: number;
  asrAverageWer?: number;
  latencyP50Ms?: number;
  realTimeFactorP50?: number;
  styleCapability?:
    "instruction_prompt" | "expressiveness_controls" | "text_only";
  listenerPreference?: number;
  notes: string;
}

export const TTS_STYLE_EVALUATION_RUN = {
  methodologyVersion: "2.0.0",
  evidenceTier: "ranked" as const,
  generatedAt: "2026-08-27T16:00:00Z",
  suite: "Vox Jot TTS Style & Emotion Benchmark v2",
  corpus:
    "Six style-specific readback prompts covering neutral, warm, excited, calm, urgent, and empathetic delivery with ASR round-trip scoring enabled.",
  limitations: "Evaluated on Apple Silicon Metal GPU and Native CPU.",
  metricGuide: [
    "Rank: #1 is best for this suite.",
    "Score and style proxy: higher is better.",
    "ASR WER: lower is better.",
    "p50 latency and RTF: lower is faster.",
  ],
  reportPath:
    "output/benchmark-v2-full-run/methodology_v2_comprehensive_report.json",
};

export const TTS_STYLE_EVALUATION_RESULTS: TtsStyleEvaluationResult[] = [
  {
    modelId: "qwen3-tts-1.7b",
    providerId: "mlx_qwen3tts",
    appModelId: "qwen3-tts-1.7b",
    label: "MLX Qwen3 TTS 1.7B VoiceDesign",
    status: "tested",
    rank: 1,
    sampleCount: 6,
    passedCases: 6,
    score: 95.8,
    asrAverageWer: 0,
    latencyP50Ms: 4753,
    realTimeFactorP50: 0.987,
    styleProxy: 0.9014,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_qwen3tts/qwen3-tts-1.7b; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-tts-1.7b-base-8bit",
    providerId: "mlx_qwen3tts",
    appModelId: "qwen3-tts-1.7b-base-8bit",
    label: "MLX Qwen3 TTS 1.7B Base 8-bit",
    status: "tested",
    rank: 2,
    sampleCount: 6,
    passedCases: 6,
    score: 95.7,
    asrAverageWer: 0.0128,
    latencyP50Ms: 4028,
    realTimeFactorP50: 0.776,
    styleProxy: 0.903,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_qwen3tts/qwen3-tts-1.7b-base-8bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "lfm2-5-audio-1-5b",
    providerId: "mlx_lfm_audio",
    appModelId: "lfm2-5-audio-1-5b",
    label: "MLX LFM2.5 Audio 1.5B",
    status: "tested",
    rank: 3,
    sampleCount: 6,
    passedCases: 6,
    score: 93.9,
    asrAverageWer: 0.0267,
    latencyP50Ms: 5068,
    realTimeFactorP50: 0.94,
    styleProxy: 0.8575,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_lfm_audio/lfm2-5-audio-1-5b; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-tts-0.6b-4bit",
    providerId: "mlx_qwen3tts",
    appModelId: "qwen3-tts-0.6b-4bit",
    label: "MLX Qwen3 TTS 0.6B 4-bit",
    status: "tested",
    rank: 4,
    sampleCount: 6,
    passedCases: 6,
    score: 93.7,
    asrAverageWer: 0.0128,
    latencyP50Ms: 3466,
    realTimeFactorP50: 0.764,
    styleProxy: 0.8326,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_qwen3tts/qwen3-tts-0.6b-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "moss-tts-nano-100m",
    providerId: "mlx_moss_tts",
    appModelId: "moss-tts-nano-100m",
    label: "MLX MOSS-TTS Nano 100M",
    status: "tested",
    rank: 5,
    sampleCount: 6,
    passedCases: 6,
    score: 91.5,
    asrAverageWer: 0.0128,
    latencyP50Ms: 3205,
    realTimeFactorP50: 0.646,
    styleProxy: 0.7535,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_moss_tts/moss-tts-nano-100m; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox-turbo",
    providerId: "chatterbox",
    appModelId: "chatterbox-turbo",
    label: "Chatterbox Turbo",
    status: "tested",
    rank: 6,
    sampleCount: 6,
    passedCases: 6,
    score: 90.3,
    asrAverageWer: 0,
    latencyP50Ms: 2926,
    realTimeFactorP50: 0.696,
    styleProxy: 0.8045,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through chatterbox/chatterbox-turbo; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "higgs-audio-v2-3b-q8",
    providerId: "mlx_higgs_audio",
    appModelId: "higgs-audio-v2-3b-q8",
    label: "MLX Higgs Audio v2 3B q8",
    status: "tested",
    rank: 7,
    sampleCount: 6,
    passedCases: 6,
    score: 90.3,
    asrAverageWer: 0.1458,
    latencyP50Ms: 6950,
    realTimeFactorP50: 1.196,
    styleProxy: 0.8593,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_higgs_audio/higgs-audio-v2-3b-q8; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "supertonic-3",
    providerId: "supertonic",
    appModelId: "supertonic-3",
    label: "Supertonic 3",
    status: "tested",
    rank: 8,
    sampleCount: 6,
    passedCases: 6,
    score: 90.3,
    asrAverageWer: 0,
    latencyP50Ms: 602,
    realTimeFactorP50: 0.106,
    styleProxy: 0.907,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through supertonic/supertonic-3; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-en-us-amy-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-en-us-amy-medium",
    label: "Sherpa Amy Medium",
    status: "tested",
    rank: 9,
    sampleCount: 6,
    passedCases: 6,
    score: 90,
    asrAverageWer: 0.0104,
    latencyP50Ms: 696,
    realTimeFactorP50: 0.135,
    styleProxy: 0.9066,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-en-us-amy-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "vibevoice-realtime-0-5b-4bit-mlx",
    providerId: "mlx_vibevoice",
    appModelId: "vibevoice-realtime-0-5b-4bit-mlx",
    label: "MLX VibeVoice Realtime 0.5B 4-bit",
    status: "tested",
    rank: 10,
    sampleCount: 6,
    passedCases: 6,
    score: 89.7,
    asrAverageWer: 0.2105,
    latencyP50Ms: 3506,
    realTimeFactorP50: 0.683,
    styleProxy: 0.8631,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_vibevoice/vibevoice-realtime-0-5b-4bit-mlx; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "lfm2-5-audio-1-5b-q4-0",
    providerId: "lfm_audio_gguf",
    appModelId: "lfm2-5-audio-1-5b-q4-0",
    label: "LFM2.5 Audio 1.5B GGUF Q4_0",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 89.2,
    asrAverageWer: 0,
    latencyP50Ms: 1662,
    realTimeFactorP50: 0.363,
    notes:
      "Full installed-app API style-suite run through lfm_audio_gguf/lfm2-5-audio-1-5b-q4-0; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.8736,
    styleCapability: "text_only",
    rank: 11,
  },
  {
    modelId: "spark-tts-0.5b",
    providerId: "mlx_spark",
    appModelId: "spark-tts-0.5b",
    label: "MLX Spark TTS 0.5B",
    status: "tested",
    rank: 12,
    sampleCount: 6,
    passedCases: 6,
    score: 88.9,
    asrAverageWer: 0.0208,
    latencyP50Ms: 4471,
    realTimeFactorP50: 0.921,
    styleProxy: 0.9165,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_spark/spark-tts-0.5b; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "system-default",
    providerId: "system_builtin",
    appModelId: "system-default",
    label: "Apple System Voice",
    status: "tested",
    rank: 13,
    sampleCount: 6,
    passedCases: 6,
    score: 88.8,
    asrAverageWer: 0.0638,
    latencyP50Ms: 424,
    realTimeFactorP50: 0.082,
    styleProxy: 0.9125,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through system_builtin/system-default; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kokoro-82m",
    providerId: "mlx_kokoro",
    appModelId: "kokoro-82m",
    label: "MLX Kokoro 82M",
    status: "tested",
    rank: 14,
    sampleCount: 6,
    passedCases: 6,
    score: 88.7,
    asrAverageWer: 0,
    latencyP50Ms: 2383,
    realTimeFactorP50: 0.494,
    styleProxy: 0.8577,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_kokoro/kokoro-82m; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "pocket-tts",
    providerId: "mlx_pocket_tts",
    appModelId: "pocket-tts",
    label: "MLX Pocket TTS",
    status: "tested",
    rank: 15,
    sampleCount: 6,
    passedCases: 6,
    score: 88.7,
    asrAverageWer: 0,
    latencyP50Ms: 2606,
    realTimeFactorP50: 0.571,
    styleProxy: 0.8642,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_pocket_tts/pocket-tts; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kokoro-82m-v1.0",
    providerId: "kokoro",
    appModelId: "kokoro-82m-v1.0",
    label: "Kokoro 82M",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 88.6,
    asrAverageWer: 0,
    latencyP50Ms: 902,
    realTimeFactorP50: 0.178,
    notes:
      "Full installed-app API style-suite run through kokoro/kokoro-82m-v1.0; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.8567,
    styleCapability: "text_only",
    rank: 16,
  },
  {
    modelId: "tts-sherpa-en-gb-alan-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-en-gb-alan-medium",
    label: "Sherpa Alan Medium",
    status: "tested",
    rank: 17,
    sampleCount: 6,
    passedCases: 6,
    score: 88.4,
    asrAverageWer: 0,
    latencyP50Ms: 685,
    realTimeFactorP50: 0.132,
    styleProxy: 0.824,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-en-gb-alan-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "outetts-1b-4bit",
    providerId: "mlx_oute",
    appModelId: "outetts-1b-4bit",
    label: "MLX Llama OuteTTS 1B 4-bit",
    status: "tested",
    rank: 18,
    sampleCount: 6,
    passedCases: 6,
    score: 88.3,
    asrAverageWer: 0,
    latencyP50Ms: 9197,
    realTimeFactorP50: 1.571,
    styleProxy: 0.9003,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_oute/outetts-1b-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "pocket-tts-4bit",
    providerId: "mlx_pocket_tts",
    appModelId: "pocket-tts-4bit",
    label: "MLX Pocket TTS 4-bit",
    status: "tested",
    rank: 19,
    sampleCount: 6,
    passedCases: 6,
    score: 88.2,
    asrAverageWer: 0,
    latencyP50Ms: 2460,
    realTimeFactorP50: 0.569,
    styleProxy: 0.8419,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_pocket_tts/pocket-tts-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "soprano-80m-4bit",
    providerId: "mlx_soprano",
    appModelId: "soprano-80m-4bit",
    label: "MLX Soprano 80M 4-bit",
    status: "tested",
    rank: 20,
    sampleCount: 6,
    passedCases: 6,
    score: 88.2,
    asrAverageWer: 0.0267,
    latencyP50Ms: 2516,
    realTimeFactorP50: 0.56,
    styleProxy: 0.8712,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_soprano/soprano-80m-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-pt-br-faber-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-pt-br-faber-medium",
    label: "Sherpa Faber Medium",
    status: "tested",
    rank: 21,
    sampleCount: 6,
    passedCases: 6,
    score: 88.2,
    asrAverageWer: 0,
    latencyP50Ms: 559,
    realTimeFactorP50: 0.136,
    styleProxy: 0.8175,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-pt-br-faber-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-de-de-thorsten-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-de-de-thorsten-medium",
    label: "Sherpa Thorsten Medium",
    status: "tested",
    rank: 22,
    sampleCount: 6,
    passedCases: 6,
    score: 88,
    asrAverageWer: 0,
    latencyP50Ms: 561,
    realTimeFactorP50: 0.13,
    styleProxy: 0.8087,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-de-de-thorsten-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-it-it-paola-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-it-it-paola-medium",
    label: "Sherpa Paola Medium",
    status: "tested",
    rank: 23,
    sampleCount: 6,
    passedCases: 6,
    score: 87.9,
    asrAverageWer: 0,
    latencyP50Ms: 558,
    realTimeFactorP50: 0.134,
    styleProxy: 0.804,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-it-it-paola-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "openvoice",
    providerId: "openvoice",
    appModelId: "openvoice",
    label: "OpenVoice",
    status: "tested",
    rank: 24,
    sampleCount: 6,
    passedCases: 6,
    score: 87.8,
    asrAverageWer: 0.0104,
    latencyP50Ms: 524,
    realTimeFactorP50: 0.119,
    styleProxy: 0.8164,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through openvoice/openvoice; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "soprano-1-1-80m-bf16",
    providerId: "mlx_soprano",
    appModelId: "soprano-1-1-80m-bf16",
    label: "MLX Soprano 1.1 80M bf16",
    status: "tested",
    rank: 25,
    sampleCount: 6,
    passedCases: 6,
    score: 87.6,
    asrAverageWer: 0,
    latencyP50Ms: 2520,
    realTimeFactorP50: 0.579,
    styleProxy: 0.8154,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_soprano/soprano-1-1-80m-bf16; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-es-es-davefx-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-es-es-davefx-medium",
    label: "Sherpa DaveFX Medium",
    status: "tested",
    rank: 26,
    sampleCount: 6,
    passedCases: 6,
    score: 87.5,
    asrAverageWer: 0.0232,
    latencyP50Ms: 560,
    realTimeFactorP50: 0.134,
    styleProxy: 0.8105,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-es-es-davefx-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "pocket-tts-8bit",
    providerId: "mlx_pocket_tts",
    appModelId: "pocket-tts-8bit",
    label: "MLX Pocket TTS 8-bit",
    status: "tested",
    rank: 27,
    sampleCount: 6,
    passedCases: 6,
    score: 87.4,
    asrAverageWer: 0,
    latencyP50Ms: 2498,
    realTimeFactorP50: 0.52,
    styleProxy: 0.8047,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_pocket_tts/pocket-tts-8bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "vibevoice-realtime-0-5b",
    providerId: "vibevoice",
    appModelId: "vibevoice-realtime-0-5b",
    label: "VibeVoice Realtime 0.5B",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 87.4,
    asrAverageWer: 0.0104,
    latencyP50Ms: 10139,
    realTimeFactorP50: 1.929,
    notes:
      "Full installed-app API style-suite run through vibevoice/vibevoice-realtime-0-5b; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.8945,
    styleCapability: "text_only",
    rank: 28,
  },
  {
    modelId: "tts-sherpa-en-us-lessac-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-en-us-lessac-medium",
    label: "Sherpa Lessac Medium",
    status: "tested",
    rank: 29,
    sampleCount: 6,
    passedCases: 6,
    score: 87.3,
    asrAverageWer: 0.0232,
    latencyP50Ms: 558,
    realTimeFactorP50: 0.137,
    styleProxy: 0.8044,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-en-us-lessac-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-fr-fr-siwis-medium",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-fr-fr-siwis-medium",
    label: "Sherpa Siwis Medium",
    status: "tested",
    rank: 30,
    sampleCount: 6,
    passedCases: 6,
    score: 87.2,
    asrAverageWer: 0.0139,
    latencyP50Ms: 556,
    realTimeFactorP50: 0.131,
    styleProxy: 0.7879,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-fr-fr-siwis-medium; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "higgs-audio-v2-3b-q6",
    providerId: "mlx_higgs_audio",
    appModelId: "higgs-audio-v2-3b-q6",
    label: "MLX Higgs Audio v2 3B q6",
    status: "tested",
    rank: 31,
    sampleCount: 6,
    passedCases: 4,
    score: 86.6,
    asrAverageWer: 0.1234,
    latencyP50Ms: 6746,
    realTimeFactorP50: 1.115,
    styleProxy: 0.8678,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_higgs_audio/higgs-audio-v2-3b-q6; 4/6 cases generated with ASR round-trip scoring. Failed cases are captured in the report and the row is ranked from the completed full-suite result.",
  },
  {
    modelId: "melotts-english",
    providerId: "mlx_melotts",
    appModelId: "melotts-english",
    label: "MLX MeloTTS English",
    status: "tested",
    rank: 32,
    sampleCount: 6,
    passedCases: 6,
    score: 86.6,
    asrAverageWer: 0.0208,
    latencyP50Ms: 4115,
    realTimeFactorP50: 0.912,
    styleProxy: 0.8115,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_melotts/melotts-english; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "longcat-audiodit-1b-bf16",
    providerId: "mlx_longcat_audiodit",
    appModelId: "longcat-audiodit-1b-bf16",
    label: "MLX LongCat AudioDiT 1B bf16",
    status: "tested",
    rank: 33,
    sampleCount: 6,
    passedCases: 6,
    score: 85.9,
    asrAverageWer: 0,
    latencyP50Ms: 5100,
    realTimeFactorP50: 1.039,
    styleProxy: 0.7631,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_longcat_audiodit/longcat-audiodit-1b-bf16; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "voxtral-tts-4b-4bit",
    providerId: "mlx_voxtral_tts",
    appModelId: "voxtral-tts-4b-4bit",
    label: "MLX Voxtral TTS 4B 4-bit",
    status: "tested",
    rank: 34,
    sampleCount: 6,
    passedCases: 6,
    score: 85.8,
    asrAverageWer: 0.1424,
    latencyP50Ms: 5404,
    realTimeFactorP50: 0.893,
    styleProxy: 0.909,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_voxtral_tts/voxtral-tts-4b-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox-mlx",
    providerId: "mlx_chatterbox",
    appModelId: "chatterbox",
    label: "MLX Chatterbox",
    status: "tested",
    rank: 35,
    sampleCount: 6,
    passedCases: 6,
    score: 85.7,
    asrAverageWer: 0.0232,
    latencyP50Ms: 5514,
    realTimeFactorP50: 1.306,
    styleProxy: 0.7949,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_chatterbox/chatterbox; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox",
    providerId: "chatterbox",
    appModelId: "chatterbox",
    label: "Chatterbox",
    status: "tested",
    rank: 36,
    sampleCount: 6,
    passedCases: 6,
    score: 85.6,
    asrAverageWer: 0,
    latencyP50Ms: 6962,
    realTimeFactorP50: 1.561,
    styleProxy: 0.6857,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through chatterbox/chatterbox; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "longcat-audiodit-3-5b-4bit",
    providerId: "mlx_longcat_audiodit",
    appModelId: "longcat-audiodit-3-5b-4bit",
    label: "MLX LongCat AudioDiT 3.5B 4-bit",
    status: "tested",
    rank: 37,
    sampleCount: 6,
    passedCases: 6,
    score: 85.6,
    asrAverageWer: 0,
    latencyP50Ms: 6493,
    realTimeFactorP50: 1.304,
    styleProxy: 0.7628,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_longcat_audiodit/longcat-audiodit-3-5b-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "dia-1.6b-4bit",
    providerId: "mlx_dia",
    appModelId: "dia-1.6b-4bit",
    label: "MLX Dia 1.6B 4-bit",
    status: "tested",
    rank: 38,
    sampleCount: 6,
    passedCases: 6,
    score: 85.5,
    asrAverageWer: 0,
    latencyP50Ms: 16314,
    realTimeFactorP50: 3.074,
    styleProxy: 0.8615,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_dia/dia-1.6b-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "dia-1.6b",
    providerId: "mlx_dia",
    appModelId: "dia-1.6b",
    label: "MLX Dia 1.6B",
    status: "tested",
    rank: 39,
    sampleCount: 6,
    passedCases: 6,
    score: 85.4,
    asrAverageWer: 0.0128,
    latencyP50Ms: 16571,
    realTimeFactorP50: 3.066,
    styleProxy: 0.8682,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_dia/dia-1.6b; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "xtts-v2",
    providerId: "xtts",
    appModelId: "xtts-v2",
    label: "XTTS v2",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 85.2,
    asrAverageWer: 0,
    latencyP50Ms: 2961,
    realTimeFactorP50: 0.533,
    notes:
      "Full installed-app API style-suite run through xtts/xtts-v2; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.7574,
    styleCapability: "text_only",
    rank: 40,
  },
  {
    modelId: "voxtral-tts-4b",
    providerId: "mlx_voxtral_tts",
    appModelId: "voxtral-tts-4b",
    label: "MLX Voxtral TTS 4B",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 84.4,
    asrAverageWer: 0.0336,
    latencyP50Ms: 21120,
    realTimeFactorP50: 3.191,
    notes:
      "Full installed-app API style-suite run through mlx_voxtral_tts/voxtral-tts-4b; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.852,
    styleCapability: "text_only",
    rank: 41,
  },
  {
    modelId: "voxcpm2-8bit",
    providerId: "mlx_voxcpm",
    appModelId: "voxcpm2-8bit",
    label: "MLX VoxCPM2 8-bit",
    status: "tested",
    rank: 42,
    sampleCount: 6,
    passedCases: 6,
    score: 83.5,
    asrAverageWer: 0.0729,
    latencyP50Ms: 7410,
    realTimeFactorP50: 1.393,
    styleProxy: 0.6697,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_voxcpm/voxcpm2-8bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "longcat-audiodit-1b-4bit",
    providerId: "mlx_longcat_audiodit",
    appModelId: "longcat-audiodit-1b-4bit",
    label: "MLX LongCat AudioDiT 1B 4-bit",
    status: "tested",
    rank: 43,
    sampleCount: 6,
    passedCases: 6,
    score: 83,
    asrAverageWer: 0.1229,
    latencyP50Ms: 4805,
    realTimeFactorP50: 0.954,
    styleProxy: 0.7661,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_longcat_audiodit/longcat-audiodit-1b-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "csm-1b-8bit",
    providerId: "mlx_csm",
    appModelId: "csm-1b-8bit",
    label: "MLX CSM 1B 8-bit",
    status: "tested",
    rank: 44,
    sampleCount: 6,
    passedCases: 6,
    score: 82.9,
    asrAverageWer: 0.0128,
    latencyP50Ms: 5374,
    realTimeFactorP50: 1.248,
    styleProxy: 0.6584,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_csm/csm-1b-8bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "voxcpm2-bf16",
    providerId: "mlx_voxcpm",
    appModelId: "voxcpm2-bf16",
    label: "MLX VoxCPM2 bf16",
    status: "tested",
    rank: 45,
    sampleCount: 6,
    passedCases: 6,
    score: 82.9,
    asrAverageWer: 0.0769,
    latencyP50Ms: 9690,
    realTimeFactorP50: 1.706,
    styleProxy: 0.633,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_voxcpm/voxcpm2-bf16; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "qwen3-0.6b-base",
    providerId: "qwen3_native",
    appModelId: "qwen3-0.6b-base",
    label: "Qwen3 Native 0.6B Base",
    status: "tested",
    rank: 46,
    sampleCount: 6,
    passedCases: 6,
    score: 82.9,
    asrAverageWer: 0.2043,
    latencyP50Ms: 4921,
    realTimeFactorP50: 0.98,
    styleProxy: 0.8608,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through qwen3_native/qwen3-0.6b-base; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "bark-small",
    providerId: "mlx_bark",
    appModelId: "bark-small",
    label: "MLX Bark Small",
    status: "tested",
    rank: 47,
    sampleCount: 6,
    passedCases: 6,
    score: 82.7,
    asrAverageWer: 0.1138,
    latencyP50Ms: 22009,
    realTimeFactorP50: 2.582,
    styleProxy: 0.8359,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_bark/bark-small; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "tts-sherpa-zh-cn-melo",
    providerId: "sherpa_pack",
    appModelId: "tts-sherpa-zh-cn-melo",
    label: "Sherpa Melo Chinese/English",
    status: "tested",
    rank: 48,
    sampleCount: 6,
    passedCases: 6,
    score: 82.3,
    asrAverageWer: 0.2404,
    latencyP50Ms: 2664,
    realTimeFactorP50: 0.54,
    styleProxy: 0.846,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through sherpa_pack/tts-sherpa-zh-cn-melo; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "csm-1b",
    providerId: "mlx_csm",
    appModelId: "csm-1b",
    label: "MLX CSM 1B",
    status: "tested",
    rank: 49,
    sampleCount: 6,
    passedCases: 6,
    score: 81.4,
    asrAverageWer: 0,
    latencyP50Ms: 8494,
    realTimeFactorP50: 2.029,
    styleProxy: 0.6206,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_csm/csm-1b; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "kugel-audio-7b",
    providerId: "mlx_kugel",
    appModelId: "kugel-audio-7b",
    label: "MLX KugelAudio 7B",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 79.6,
    asrAverageWer: 0,
    latencyP50Ms: 59800,
    realTimeFactorP50: 13.171,
    notes:
      "Full installed-app API style-suite run through mlx_kugel/kugel-audio-7b; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.8715,
    styleCapability: "text_only",
    rank: 50,
  },
  {
    modelId: "spark-tts-0.5b-4-6bit",
    providerId: "mlx_spark",
    appModelId: "spark-tts-0.5b-4-6bit",
    label: "MLX Spark TTS 0.5B 4/6-bit",
    status: "tested",
    rank: 51,
    sampleCount: 6,
    passedCases: 2,
    score: 79.6,
    asrAverageWer: 0.0416,
    latencyP50Ms: 3894,
    realTimeFactorP50: 0.803,
    styleProxy: 0.9621,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_spark/spark-tts-0.5b-4-6bit; 2/6 cases generated with ASR round-trip scoring. Failed cases are captured in the report and the row is ranked from the completed full-suite result.",
  },
  {
    modelId: "voxcpm2-4bit",
    providerId: "mlx_voxcpm",
    appModelId: "voxcpm2-4bit",
    label: "MLX VoxCPM2 4-bit",
    status: "tested",
    rank: 52,
    sampleCount: 6,
    passedCases: 6,
    score: 78.3,
    asrAverageWer: 0.2065,
    latencyP50Ms: 6482,
    realTimeFactorP50: 1.438,
    styleProxy: 0.5582,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_voxcpm/voxcpm2-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "indextts-1-5",
    providerId: "mlx_indextts",
    appModelId: "indextts-1-5",
    label: "MLX IndexTTS 1.5",
    status: "tested",
    rank: 53,
    sampleCount: 6,
    passedCases: 6,
    score: 76.4,
    asrAverageWer: 0.3077,
    latencyP50Ms: 4992,
    realTimeFactorP50: 1.319,
    styleProxy: 0.6986,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_indextts/indextts-1-5; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "chatterbox-multilingual",
    providerId: "chatterbox",
    appModelId: "chatterbox-multilingual",
    label: "Chatterbox Multilingual",
    status: "tested",
    rank: 54,
    sampleCount: 6,
    passedCases: 5,
    score: 76,
    asrAverageWer: 0.2875,
    latencyP50Ms: 6587,
    realTimeFactorP50: 1.716,
    styleProxy: 0.676,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through chatterbox/chatterbox-multilingual; 5/6 cases generated with ASR round-trip scoring. Failed cases are captured in the report and the row is ranked from the completed full-suite result.",
  },
  {
    modelId: "irodori-tts-500m-v2-4bit",
    providerId: "mlx_irodori_tts",
    appModelId: "irodori-tts-500m-v2-4bit",
    label: "MLX Irodori TTS 500M v2 4-bit",
    status: "tested",
    rank: 55,
    sampleCount: 6,
    passedCases: 6,
    score: 72.9,
    asrAverageWer: 0.7639,
    latencyP50Ms: 12790,
    realTimeFactorP50: 2.114,
    styleProxy: 0.8191,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_irodori_tts/irodori-tts-500m-v2-4bit; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "ming-omni-0.5b",
    providerId: "mlx_ming_omni",
    appModelId: "ming-omni-0.5b",
    label: "MLX Ming-omni TTS 0.5B",
    status: "tested",
    rank: 56,
    sampleCount: 6,
    passedCases: 6,
    score: 70.7,
    asrAverageWer: 0.8568,
    latencyP50Ms: 4896,
    realTimeFactorP50: 0.471,
    styleProxy: 0.7608,
    styleCapability: "instruction_prompt",
    notes:
      "Full installed-app API style-suite run through mlx_ming_omni/ming-omni-0.5b; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "fish-audio-s2-pro",
    providerId: "mlx_fish_audio",
    appModelId: "fish-audio-s2-pro",
    label: "MLX Fish Audio S2 Pro",
    status: "tested",
    rank: 57,
    sampleCount: 6,
    passedCases: 6,
    score: 65.1,
    asrAverageWer: 0.8157,
    latencyP50Ms: 20339,
    realTimeFactorP50: 2.165,
    styleProxy: 0.8087,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_fish_audio/fish-audio-s2-pro; 6/6 cases generated with ASR round-trip scoring.",
  },
  {
    modelId: "omnivoice",
    providerId: "mlx_omnivoice",
    appModelId: "omnivoice",
    label: "MLX OmniVoice",
    status: "tested",
    sampleCount: 6,
    passedCases: 6,
    score: 64.9,
    asrAverageWer: 1.7067,
    latencyP50Ms: 6047,
    realTimeFactorP50: 1.15,
    notes:
      "Full installed-app API style-suite run through mlx_omnivoice/omnivoice; 6/6 cases generated with ASR round-trip scoring.",
    styleProxy: 0.7297,
    styleCapability: "instruction_prompt",
    rank: 58,
  },
  {
    modelId: "fish-audio-s2-pro-8bit",
    providerId: "mlx_fish_audio",
    appModelId: "fish-audio-s2-pro-8bit",
    label: "MLX Fish Audio S2 Pro 8-bit",
    status: "tested",
    rank: 59,
    sampleCount: 6,
    passedCases: 6,
    score: 61.5,
    asrAverageWer: 1.9741,
    latencyP50Ms: 12139,
    realTimeFactorP50: 1.432,
    styleProxy: 0.8145,
    styleCapability: "text_only",
    notes:
      "Full installed-app API style-suite run through mlx_fish_audio/fish-audio-s2-pro-8bit; 6/6 cases generated with ASR round-trip scoring.",
  },
];

export function getTtsStyleEvaluationResult(
  modelId: string,
): TtsStyleEvaluationResult | undefined {
  return TTS_STYLE_EVALUATION_RESULTS.find(
    (result) => result.modelId === modelId,
  );
}
