export type TtsVoiceCloneEvaluationStatus = "tested" | "failed" | "blocked";

export interface TtsVoiceCloneEvaluationResult {
  modelId: string;
  label: string;
  status: TtsVoiceCloneEvaluationStatus;
  rank?: number;
  sampleCount?: number;
  passedCases?: number;
  score?: number;
  cloneSimilarity?: number;
  asrAverageWer?: number;
  latencyP50Ms?: number;
  realTimeFactorP50?: number;
  listenerPreference?: number;
  notes: string;
}

export const TTS_VOICE_CLONE_EVALUATION_RUN = {
  generatedAt: "2026-05-12T03:37:44Z",
  suite: "TTS voice cloning real-world benchmark",
  corpus:
    "Four reference-conditioned clone prompts covering casual reply, meeting-room summary, code-review dictation, and noisy real-world correction text. Every clone-capable installed model was tested with the same bundled reference WAV.",
  limitations:
    "Speaker match is an automatic acoustic-fingerprint proxy, not a human MOS or ABX speaker-similarity panel. Scores also include ASR round-trip WER, WAV health, synthesis success, and real-time factor.",
  metricGuide: [
    "Rank: #1 is best for this suite.",
    "Score, pass, and clone similarity: higher is better.",
    "ASR WER: lower is better.",
    "p50 latency and RTF: lower is faster.",
    "Listener preference is scaffolded in the CSV but not yet collected.",
  ],
  reportPath:
    "output/tts-voice-clone-eval/full-new-mlx-2026-05-11/tts-voice-clone-eval-summary.json",
};

export const TTS_VOICE_CLONE_EVALUATION_RESULTS: TtsVoiceCloneEvaluationResult[] =
  [
    {
      modelId: "qwen3-tts-1.7b-base-8bit",
      label: "MLX Qwen3 TTS 1.7B Base 8-bit",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 91.8,
      cloneSimilarity: 0.8498,
      asrAverageWer: 0.0114,
      latencyP50Ms: 10146,
      realTimeFactorP50: 1.56,
      notes:
        "Best new MLX-Audio clone result; four-case full suite combined high clone proxy with low ASR WER.",
      rank: 1,
    },
    {
      modelId: "qwen3-tts-1.7b-base",
      label: "MLX Qwen3 TTS 1.7B Base",
      status: "tested",
      rank: 2,
      sampleCount: 4,
      passedCases: 4,
      score: 90.2,
      cloneSimilarity: 0.8067,
      asrAverageWer: 0.0114,
      latencyP50Ms: 13754,
      realTimeFactorP50: 1.91,
      notes:
        "Best overall clone score after removing instruction echo from the MLX clone path.",
    },
    {
      modelId: "moss-tts-nano-100m",
      label: "MLX MOSS-TTS Nano 100M",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 90.1,
      cloneSimilarity: 0.781,
      asrAverageWer: 0.0352,
      latencyP50Ms: 5807,
      realTimeFactorP50: 0.798,
      notes:
        "Full clone suite passed using the bundled fallback conditioning prompt, with strong clone proxy and low WER.",
      rank: 3,
    },
    {
      modelId: "qwen3-tts-0.6b-4bit",
      label: "MLX Qwen3 TTS 0.6B 4-bit",
      status: "tested",
      rank: 4,
      sampleCount: 4,
      passedCases: 4,
      score: 89.8,
      cloneSimilarity: 0.7539,
      asrAverageWer: 0.028,
      latencyP50Ms: 4711,
      realTimeFactorP50: 0.672,
      notes: "Strong speed and clone-quality balance among Qwen3 variants.",
    },
    {
      modelId: "pocket-tts",
      label: "MLX Pocket TTS",
      status: "tested",
      rank: 5,
      sampleCount: 4,
      passedCases: 4,
      score: 89.7,
      cloneSimilarity: 0.726,
      asrAverageWer: 0.0114,
      latencyP50Ms: 3110,
      realTimeFactorP50: 0.426,
      notes: "Fast full-precision Pocket TTS clone result with low WER.",
    },
    {
      modelId: "qwen3-tts-0.6b",
      label: "MLX Qwen3 TTS 0.6B",
      status: "tested",
      rank: 6,
      sampleCount: 4,
      passedCases: 4,
      score: 89.6,
      cloneSimilarity: 0.777,
      asrAverageWer: 0.0233,
      latencyP50Ms: 9618,
      realTimeFactorP50: 1.383,
      notes: "High clone-similarity proxy with slightly slower p50 than 4-bit.",
    },
    {
      modelId: "pocket-tts-8bit",
      label: "MLX Pocket TTS 8-bit",
      status: "tested",
      rank: 7,
      sampleCount: 4,
      passedCases: 4,
      score: 89.5,
      cloneSimilarity: 0.714,
      asrAverageWer: 0.0114,
      latencyP50Ms: 2799,
      realTimeFactorP50: 0.4,
      notes: "Fastest top-five clone model in this run.",
    },
    {
      modelId: "pocket-tts-4bit",
      label: "MLX Pocket TTS 4-bit",
      status: "tested",
      rank: 8,
      sampleCount: 4,
      passedCases: 4,
      score: 89.1,
      cloneSimilarity: 0.7017,
      asrAverageWer: 0.0114,
      latencyP50Ms: 2884,
      realTimeFactorP50: 0.414,
      notes: "Low WER and fast synthesis, with lower clone proxy than 8-bit.",
    },
    {
      modelId: "csm-1b",
      label: "MLX CSM 1B",
      status: "tested",
      rank: 9,
      sampleCount: 4,
      passedCases: 4,
      score: 89,
      cloneSimilarity: 0.7526,
      asrAverageWer: 0.0114,
      latencyP50Ms: 12607,
      realTimeFactorP50: 1.783,
      notes: "Reference-conditioned CSM path passed every clone case.",
    },
    {
      modelId: "fish-audio-s2-pro",
      label: "MLX Fish Audio S2 Pro",
      status: "tested",
      rank: 10,
      sampleCount: 4,
      passedCases: 4,
      score: 88.8,
      cloneSimilarity: 0.7897,
      asrAverageWer: 0.0114,
      latencyP50Ms: 18613,
      realTimeFactorP50: 2.621,
      notes: "High clone proxy and low WER, with slower p50 latency.",
    },
    {
      modelId: "longcat-audiodit-1b-4bit",
      label: "MLX LongCat AudioDiT 1B 4-bit",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 84.1,
      cloneSimilarity: 0.5934,
      asrAverageWer: 0.0114,
      latencyP50Ms: 14057,
      realTimeFactorP50: 1.681,
      notes:
        "Full clone suite passed with very low WER and moderate clone-similarity proxy.",
      rank: 11,
    },
    {
      modelId: "qwen3-tts-1.7b",
      label: "MLX Qwen3 TTS 1.7B VoiceDesign",
      status: "tested",
      rank: 12,
      sampleCount: 4,
      passedCases: 4,
      score: 83.3,
      cloneSimilarity: 0.528,
      asrAverageWer: 0.0233,
      latencyP50Ms: 6189,
      realTimeFactorP50: 0.854,
      notes:
        "VoiceDesign stayed intelligible but scored lower on clone similarity.",
    },
    {
      modelId: "csm-1b-8bit",
      label: "MLX CSM 1B 8-bit",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 83.3,
      cloneSimilarity: 0.7693,
      asrAverageWer: 0.2447,
      latencyP50Ms: 16719,
      realTimeFactorP50: 1.595,
      notes:
        "Full clone suite passed using the bundled fallback conditioning prompt.",
      rank: 13,
    },
    {
      modelId: "xtts-v2",
      label: "XTTS v2",
      status: "tested",
      rank: 14,
      sampleCount: 4,
      passedCases: 4,
      score: 82.5,
      cloneSimilarity: 0.5613,
      asrAverageWer: 0.0114,
      latencyP50Ms: 22417,
      realTimeFactorP50: 2.668,
      notes:
        "Reliable XTTS clone path, but slower than the leading MLX options.",
    },
    {
      modelId: "qwen3-0.6b-base",
      label: "Qwen3 Native 0.6B Base",
      status: "tested",
      rank: 15,
      sampleCount: 4,
      passedCases: 4,
      score: 81.9,
      cloneSimilarity: 0.6661,
      asrAverageWer: 0.2393,
      latencyP50Ms: 12898,
      realTimeFactorP50: 1.769,
      notes:
        "Native Qwen3 clone binary ran all cases, with higher WER than MLX Qwen3.",
    },
    {
      modelId: "ming-omni-0.5b",
      label: "MLX Ming-omni TTS 0.5B",
      status: "tested",
      rank: 16,
      sampleCount: 4,
      passedCases: 4,
      score: 81.7,
      cloneSimilarity: 0.6545,
      asrAverageWer: 0.2419,
      latencyP50Ms: 5614,
      realTimeFactorP50: 0.721,
      notes:
        "Improved after disabling default instruction injection, but still has elevated WER on hard clone prompts.",
    },
    {
      modelId: "chatterbox-multilingual",
      label: "Chatterbox Multilingual",
      status: "tested",
      rank: 17,
      sampleCount: 4,
      passedCases: 4,
      score: 78.5,
      cloneSimilarity: 0.6997,
      asrAverageWer: 0.2278,
      latencyP50Ms: 23859,
      realTimeFactorP50: 5.612,
      notes:
        "Good clone proxy, but slower and less accurate on ASR round-trip.",
    },
    {
      modelId: "openvoice",
      label: "OpenVoice",
      status: "tested",
      rank: 18,
      sampleCount: 4,
      passedCases: 4,
      score: 75.2,
      cloneSimilarity: 0.2524,
      asrAverageWer: 0.0233,
      latencyP50Ms: 7395,
      realTimeFactorP50: 1.127,
      notes:
        "Intelligible tone-conversion output, but low acoustic-fingerprint similarity to the bundled reference.",
    },
    {
      modelId: "qwen3-tts-0.6b-customvoice",
      label: "MLX Qwen3 TTS 0.6B CustomVoice",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 74.4,
      cloneSimilarity: 0.259,
      asrAverageWer: 0.0471,
      latencyP50Ms: 8765,
      realTimeFactorP50: 1.588,
      notes:
        "Full clone suite passed with low WER, but lower clone-similarity proxy than the 1.7B Base row.",
      rank: 19,
    },
    {
      modelId: "chatterbox-turbo",
      label: "Chatterbox Turbo",
      status: "tested",
      rank: 20,
      sampleCount: 4,
      passedCases: 4,
      score: 72.7,
      cloneSimilarity: 0.2381,
      asrAverageWer: 0.0114,
      latencyP50Ms: 19207,
      realTimeFactorP50: 2.804,
      notes:
        "Very intelligible, but the automatic clone-similarity proxy did not match the reference closely.",
    },
    {
      modelId: "irodori-tts-500m-v2-4bit",
      label: "MLX Irodori TTS 500M v2 4-bit",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 68.5,
      cloneSimilarity: 0.7516,
      asrAverageWer: 0.8163,
      latencyP50Ms: 14401,
      realTimeFactorP50: 1.924,
      notes:
        "Full clone suite passed, but ASR WER kept it below the stronger clone rows.",
      rank: 21,
    },
    {
      modelId: "voxcpm2-4bit",
      label: "MLX VoxCPM2 4-bit",
      status: "tested",
      rank: 22,
      sampleCount: 4,
      passedCases: 4,
      score: 64,
      cloneSimilarity: 0.3026,
      asrAverageWer: 0.5281,
      latencyP50Ms: 13532,
      realTimeFactorP50: 1.125,
      notes:
        "Default instruction echo was fixed, but this run still showed high WER and weak clone proxy.",
    },
    {
      modelId: "fish-audio-s2-pro-8bit",
      label: "MLX Fish Audio S2 Pro 8-bit",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 57.5,
      cloneSimilarity: 0.3511,
      asrAverageWer: 0.7808,
      latencyP50Ms: 20063,
      realTimeFactorP50: 1.504,
      notes:
        "Full clone suite passed, but weak ASR round-trip accuracy kept it at the bottom of the new clone set.",
      rank: 23,
    },
    {
      modelId: "indextts-1-5",
      label: "MLX IndexTTS 1.5",
      status: "failed",
      sampleCount: 4,
      passedCases: 0,
      notes:
        "Full four-case voice-clone suite failed in the MLX bridge because the current IndexTTS runtime requires tokenizer_name in ModelArgs.",
    },
  ];
