export type TtsVoiceCloneEvaluationStatus = "tested" | "failed" | "blocked";

export interface TtsVoiceCloneEvaluationResult {
  modelId: string;
  providerId?: string;
  appModelId?: string;
  label: string;
  status: TtsVoiceCloneEvaluationStatus;
  rank?: number;
  sampleCount?: number;
  passedCases?: number;
  score?: number;
  cloneSimilarity?: number;
  asrAverageWer?: number;
  latencyP50Ms?: number;
  realTimeFactorP50?: number;
  listenerPreference?: number;
  notes: string;
}

export const TTS_VOICE_CLONE_EVALUATION_RUN = {
  methodologyVersion: "1.0-legacy",
  evidenceTier: "legacy" as const,
  generatedAt: "2026-05-21T03:46:54Z",
  suite: "tts_voice_clone_real_world_hard",
  corpus:
    "Four reference-conditioned clone prompts covering casual reply, meeting-room summary, code-review dictation, and noisy real-world correction text. Every clone-capable installed model was tested through the installed Vox Jot app local API with the same bundled reference WAV.",
  limitations:
    "Speaker match is an automatic acoustic-fingerprint proxy, not a human MOS or ABX speaker-similarity panel. Scores also include ASR round-trip WER, WAV health, synthesis success, and real-time factor.",
  metricGuide: [
    "Rank: #1 is best for this installed-app suite.",
    "Score, pass, and clone similarity: higher is better.",
    "ASR WER: lower is better.",
    "p50 latency and RTF: lower is faster.",
    "Listener preference is scaffolded in the CSV but not yet collected.",
    "AA Elo (external): Artificial Analysis provider-voice arena context retrieved 2026-08-27; it never affects Vox Jot's local score or rank.",
  ],
  reportPath:
    "output/tts-voice-clone-eval/app-full-2026-05-21-fixed-merged/tts-voice-clone-eval-summary.json",
};

export const TTS_VOICE_CLONE_EVALUATION_RESULTS: TtsVoiceCloneEvaluationResult[] =
  [
    {
      modelId: "csm-1b-8bit",
      providerId: "mlx_csm",
      appModelId: "csm-1b-8bit",
      label: "MLX CSM 1B 8-bit",
      status: "tested",
      rank: 1,
      sampleCount: 4,
      passedCases: 4,
      score: 91.6,
      asrAverageWer: 0.0518,
      latencyP50Ms: 6398,
      realTimeFactorP50: 0.999,
      cloneSimilarity: 0.8535,
      notes:
        "Full installed-app API voice-clone suite run through mlx_csm/csm-1b-8bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "moss-tts-nano-100m",
      providerId: "mlx_moss_tts",
      appModelId: "moss-tts-nano-100m",
      label: "MLX MOSS-TTS Nano 100M",
      status: "tested",
      rank: 2,
      sampleCount: 4,
      passedCases: 4,
      score: 91.5,
      asrAverageWer: 0.0114,
      latencyP50Ms: 3552,
      realTimeFactorP50: 0.528,
      cloneSimilarity: 0.7892,
      notes:
        "Full installed-app API voice-clone suite run through mlx_moss_tts/moss-tts-nano-100m; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "csm-1b",
      providerId: "mlx_csm",
      appModelId: "csm-1b",
      label: "MLX CSM 1B",
      status: "tested",
      rank: 3,
      sampleCount: 4,
      passedCases: 4,
      score: 91.1,
      asrAverageWer: 0.0233,
      latencyP50Ms: 11406,
      realTimeFactorP50: 1.844,
      cloneSimilarity: 0.8448,
      notes:
        "Full installed-app API voice-clone suite run through mlx_csm/csm-1b; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "longcat-audiodit-1b-bf16",
      providerId: "mlx_longcat_audiodit",
      appModelId: "longcat-audiodit-1b-bf16",
      label: "MLX LongCat AudioDiT 1B bf16",
      status: "tested",
      rank: 4,
      sampleCount: 4,
      passedCases: 4,
      score: 87.9,
      asrAverageWer: 0.0352,
      latencyP50Ms: 5762,
      realTimeFactorP50: 0.681,
      cloneSimilarity: 0.6954,
      notes:
        "Full installed-app API voice-clone suite run through mlx_longcat_audiodit/longcat-audiodit-1b-bf16; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "longcat-audiodit-1b-4bit",
      providerId: "mlx_longcat_audiodit",
      appModelId: "longcat-audiodit-1b-4bit",
      label: "MLX LongCat AudioDiT 1B 4-bit",
      status: "tested",
      rank: 5,
      sampleCount: 4,
      passedCases: 4,
      score: 87.3,
      asrAverageWer: 0.0352,
      latencyP50Ms: 5474,
      realTimeFactorP50: 0.649,
      cloneSimilarity: 0.6719,
      notes:
        "Full installed-app API voice-clone suite run through mlx_longcat_audiodit/longcat-audiodit-1b-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "longcat-audiodit-3-5b-4bit",
      providerId: "mlx_longcat_audiodit",
      appModelId: "longcat-audiodit-3-5b-4bit",
      label: "MLX LongCat AudioDiT 3.5B 4-bit",
      status: "tested",
      rank: 6,
      sampleCount: 4,
      passedCases: 4,
      score: 86.3,
      asrAverageWer: 0.0352,
      latencyP50Ms: 8451,
      realTimeFactorP50: 1,
      cloneSimilarity: 0.6523,
      notes:
        "Full installed-app API voice-clone suite run through mlx_longcat_audiodit/longcat-audiodit-3-5b-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "pocket-tts",
      providerId: "mlx_pocket_tts",
      appModelId: "pocket-tts",
      label: "MLX Pocket TTS",
      status: "tested",
      rank: 7,
      sampleCount: 4,
      passedCases: 4,
      score: 84.6,
      asrAverageWer: 0.0114,
      latencyP50Ms: 2810,
      realTimeFactorP50: 0.401,
      cloneSimilarity: 0.545,
      notes:
        "Full installed-app API voice-clone suite run through mlx_pocket_tts/pocket-tts; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "pocket-tts-8bit",
      providerId: "mlx_pocket_tts",
      appModelId: "pocket-tts-8bit",
      label: "MLX Pocket TTS 8-bit",
      status: "tested",
      rank: 8,
      sampleCount: 4,
      passedCases: 4,
      score: 84.2,
      asrAverageWer: 0.0114,
      latencyP50Ms: 2598,
      realTimeFactorP50: 0.352,
      cloneSimilarity: 0.5251,
      notes:
        "Full installed-app API voice-clone suite run through mlx_pocket_tts/pocket-tts-8bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "omnivoice",
      providerId: "mlx_omnivoice",
      appModelId: "omnivoice",
      label: "MLX OmniVoice",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 83.2,
      asrAverageWer: 0.0114,
      latencyP50Ms: 7196,
      realTimeFactorP50: 0.847,
      notes:
        "Full installed-app API voice-clone suite run through mlx_omnivoice/omnivoice; 4/4 cases generated with ASR round-trip scoring.",
      cloneSimilarity: 0.515,
      rank: 9,
    },
    {
      modelId: "pocket-tts-4bit",
      providerId: "mlx_pocket_tts",
      appModelId: "pocket-tts-4bit",
      label: "MLX Pocket TTS 4-bit",
      status: "tested",
      rank: 10,
      sampleCount: 4,
      passedCases: 4,
      score: 82.1,
      asrAverageWer: 0.0114,
      latencyP50Ms: 2572,
      realTimeFactorP50: 0.351,
      cloneSimilarity: 0.4531,
      notes:
        "Full installed-app API voice-clone suite run through mlx_pocket_tts/pocket-tts-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "indextts-1-5",
      providerId: "mlx_indextts",
      appModelId: "indextts-1-5",
      label: "MLX IndexTTS 1.5",
      status: "tested",
      rank: 11,
      sampleCount: 4,
      passedCases: 4,
      score: 81.4,
      asrAverageWer: 0.2877,
      latencyP50Ms: 5784,
      realTimeFactorP50: 1.149,
      cloneSimilarity: 0.7061,
      notes:
        "Full installed-app API voice-clone suite run through mlx_indextts/indextts-1-5; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "outetts-1b-4bit",
      providerId: "mlx_oute",
      appModelId: "outetts-1b-4bit",
      label: "MLX Llama OuteTTS 1B 4-bit",
      status: "tested",
      rank: 12,
      sampleCount: 4,
      passedCases: 4,
      score: 81.4,
      asrAverageWer: 0.1266,
      latencyP50Ms: 10070,
      realTimeFactorP50: 1.512,
      cloneSimilarity: 0.582,
      notes:
        "Full installed-app API voice-clone suite run through mlx_oute/outetts-1b-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "qwen3-tts-1.7b",
      providerId: "mlx_qwen3tts",
      appModelId: "qwen3-tts-1.7b",
      label: "MLX Qwen3 TTS 1.7B VoiceDesign",
      status: "tested",
      rank: 13,
      sampleCount: 4,
      passedCases: 4,
      score: 79.9,
      asrAverageWer: 0.0114,
      latencyP50Ms: 5638,
      realTimeFactorP50: 0.805,
      cloneSimilarity: 0.3999,
      notes:
        "Full installed-app API voice-clone suite run through mlx_qwen3tts/qwen3-tts-1.7b; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "xtts-v2",
      providerId: "xtts",
      appModelId: "xtts-v2",
      label: "XTTS v2",
      status: "tested",
      sampleCount: 4,
      passedCases: 4,
      score: 78.4,
      asrAverageWer: 0.1185,
      latencyP50Ms: 9780,
      realTimeFactorP50: 0.538,
      notes:
        "Full installed-app API voice-clone suite run through xtts/xtts-v2; 4/4 cases generated with ASR round-trip scoring.",
      cloneSimilarity: 0.4759,
      rank: 14,
    },
    {
      modelId: "openvoice",
      providerId: "openvoice",
      appModelId: "openvoice",
      label: "OpenVoice",
      status: "tested",
      rank: 15,
      sampleCount: 4,
      passedCases: 4,
      score: 77.2,
      asrAverageWer: 0.0233,
      latencyP50Ms: 640,
      realTimeFactorP50: 0.11,
      cloneSimilarity: 0.2642,
      notes:
        "Full installed-app API voice-clone suite run through openvoice/openvoice; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "chatterbox-turbo",
      providerId: "chatterbox",
      appModelId: "chatterbox-turbo",
      label: "Chatterbox Turbo",
      status: "tested",
      rank: 16,
      sampleCount: 4,
      passedCases: 4,
      score: 76.9,
      asrAverageWer: 0.0114,
      latencyP50Ms: 4812,
      realTimeFactorP50: 0.654,
      cloneSimilarity: 0.283,
      notes:
        "Full installed-app API voice-clone suite run through chatterbox/chatterbox-turbo; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "qwen3-tts-0.6b-4bit",
      providerId: "mlx_qwen3tts",
      appModelId: "qwen3-tts-0.6b-4bit",
      label: "MLX Qwen3 TTS 0.6B 4-bit",
      status: "tested",
      rank: 17,
      sampleCount: 4,
      passedCases: 4,
      score: 74.9,
      asrAverageWer: 0.0114,
      latencyP50Ms: 4216,
      realTimeFactorP50: 0.544,
      cloneSimilarity: 0.209,
      notes:
        "Full installed-app API voice-clone suite run through mlx_qwen3tts/qwen3-tts-0.6b-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "qwen3-tts-1.7b-base-8bit",
      providerId: "mlx_qwen3tts",
      appModelId: "qwen3-tts-1.7b-base-8bit",
      label: "MLX Qwen3 TTS 1.7B Base 8-bit",
      status: "tested",
      rank: 18,
      sampleCount: 4,
      passedCases: 4,
      score: 74.3,
      asrAverageWer: 0.0114,
      latencyP50Ms: 4342,
      realTimeFactorP50: 0.688,
      cloneSimilarity: 0.1952,
      notes:
        "Full installed-app API voice-clone suite run through mlx_qwen3tts/qwen3-tts-1.7b-base-8bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "higgs-audio-v2-3b-q8",
      providerId: "mlx_higgs_audio",
      appModelId: "higgs-audio-v2-3b-q8",
      label: "MLX Higgs Audio v2 3B q8",
      status: "tested",
      rank: 19,
      sampleCount: 4,
      passedCases: 4,
      score: 70.5,
      asrAverageWer: 0.178,
      latencyP50Ms: 9718,
      realTimeFactorP50: 0.913,
      cloneSimilarity: 0.2458,
      notes:
        "Full installed-app API voice-clone suite run through mlx_higgs_audio/higgs-audio-v2-3b-q8; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "qwen3-0.6b-base",
      providerId: "qwen3_native",
      appModelId: "qwen3-0.6b-base",
      label: "Qwen3 Native 0.6B Base",
      status: "tested",
      rank: 20,
      sampleCount: 4,
      passedCases: 4,
      score: 70,
      asrAverageWer: 0.1774,
      latencyP50Ms: 7799,
      realTimeFactorP50: 1.143,
      cloneSimilarity: 0.1968,
      notes:
        "Full installed-app API voice-clone suite run through qwen3_native/qwen3-0.6b-base; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "chatterbox-multilingual",
      providerId: "chatterbox",
      appModelId: "chatterbox-multilingual",
      label: "Chatterbox Multilingual",
      status: "tested",
      rank: 21,
      sampleCount: 4,
      passedCases: 4,
      score: 68.5,
      asrAverageWer: 0.473,
      latencyP50Ms: 10566,
      realTimeFactorP50: 2.51,
      cloneSimilarity: 0.641,
      notes:
        "Full installed-app API voice-clone suite run through chatterbox/chatterbox-multilingual; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "voxcpm2-4bit",
      providerId: "mlx_voxcpm",
      appModelId: "voxcpm2-4bit",
      label: "MLX VoxCPM2 4-bit",
      status: "tested",
      rank: 22,
      sampleCount: 4,
      passedCases: 4,
      score: 65.8,
      asrAverageWer: 0.3337,
      latencyP50Ms: 7688,
      realTimeFactorP50: 1.265,
      cloneSimilarity: 0.3098,
      notes:
        "Full installed-app API voice-clone suite run through mlx_voxcpm/voxcpm2-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "irodori-tts-500m-v2-4bit",
      providerId: "mlx_irodori_tts",
      appModelId: "irodori-tts-500m-v2-4bit",
      label: "MLX Irodori TTS 500M v2 4-bit",
      status: "tested",
      rank: 23,
      sampleCount: 4,
      passedCases: 4,
      score: 64.9,
      asrAverageWer: 0.743,
      latencyP50Ms: 12737,
      realTimeFactorP50: 1.506,
      cloneSimilarity: 0.5426,
      notes:
        "Full installed-app API voice-clone suite run through mlx_irodori_tts/irodori-tts-500m-v2-4bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "voxcpm2-bf16",
      providerId: "mlx_voxcpm",
      appModelId: "voxcpm2-bf16",
      label: "MLX VoxCPM2 bf16",
      status: "tested",
      rank: 24,
      sampleCount: 4,
      passedCases: 4,
      score: 64.9,
      asrAverageWer: 0.3371,
      latencyP50Ms: 11210,
      realTimeFactorP50: 1.612,
      cloneSimilarity: 0.3002,
      notes:
        "Full installed-app API voice-clone suite run through mlx_voxcpm/voxcpm2-bf16; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "ming-omni-0.5b",
      providerId: "mlx_ming_omni",
      appModelId: "ming-omni-0.5b",
      label: "MLX Ming-omni TTS 0.5B",
      status: "tested",
      rank: 25,
      sampleCount: 4,
      passedCases: 4,
      score: 60.8,
      asrAverageWer: 0.9297,
      latencyP50Ms: 6260,
      realTimeFactorP50: 0.444,
      cloneSimilarity: 0.5132,
      notes:
        "Full installed-app API voice-clone suite run through mlx_ming_omni/ming-omni-0.5b; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "higgs-audio-v2-3b-q6",
      providerId: "mlx_higgs_audio",
      appModelId: "higgs-audio-v2-3b-q6",
      label: "MLX Higgs Audio v2 3B q6",
      status: "tested",
      rank: 26,
      sampleCount: 4,
      passedCases: 3,
      score: 59.7,
      asrAverageWer: 0.3831,
      latencyP50Ms: 26529,
      realTimeFactorP50: 0.558,
      cloneSimilarity: 0.2045,
      notes:
        "Full installed-app API voice-clone suite run through mlx_higgs_audio/higgs-audio-v2-3b-q6; 3/4 cases generated with ASR round-trip scoring. Failed cases are captured in the report and the row is ranked from the completed full-suite result.",
    },
    {
      modelId: "fish-audio-s2-pro-8bit",
      providerId: "mlx_fish_audio",
      appModelId: "fish-audio-s2-pro-8bit",
      label: "MLX Fish Audio S2 Pro 8-bit",
      status: "tested",
      rank: 27,
      sampleCount: 4,
      passedCases: 4,
      score: 59,
      asrAverageWer: 0.9947,
      latencyP50Ms: 17298,
      realTimeFactorP50: 1.272,
      cloneSimilarity: 0.542,
      notes:
        "Full installed-app API voice-clone suite run through mlx_fish_audio/fish-audio-s2-pro-8bit; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "fish-audio-s2-pro",
      providerId: "mlx_fish_audio",
      appModelId: "fish-audio-s2-pro",
      label: "MLX Fish Audio S2 Pro",
      status: "tested",
      rank: 28,
      sampleCount: 4,
      passedCases: 4,
      score: 51.5,
      asrAverageWer: 1.005,
      latencyP50Ms: 28885,
      realTimeFactorP50: 2.038,
      cloneSimilarity: 0.3192,
      notes:
        "Full installed-app API voice-clone suite run through mlx_fish_audio/fish-audio-s2-pro; 4/4 cases generated with ASR round-trip scoring.",
    },
    {
      modelId: "voxcpm2-8bit",
      providerId: "mlx_voxcpm",
      appModelId: "voxcpm2-8bit",
      label: "MLX VoxCPM2 8-bit",
      status: "tested",
      rank: 29,
      sampleCount: 4,
      passedCases: 4,
      score: 48.6,
      asrAverageWer: 1.6197,
      latencyP50Ms: 8222,
      realTimeFactorP50: 1.269,
      cloneSimilarity: 0.2935,
      notes:
        "Full installed-app API voice-clone suite run through mlx_voxcpm/voxcpm2-8bit; 4/4 cases generated with ASR round-trip scoring.",
    },
  ];
